### ISSUE TITLE
Feat: Implement the function of `BasicMultiCall` contract.

### ISSUE THREAD

**Issue by Sk8erboi84** [keep-starknet-strange/satoru#238]
## Description

Implement `multicall` function in the `BasicMulticall` contract.

File: `src/utils/basic_multicall.cairo`.

Function signature:
```rust
    /// Receives and executes a batch of function calls on this contract.
    /// # Arguments
    /// * `data` - calls to execute.
    fn multicall(data: Array<Array<felt252>>) -> Array<Array<felt252>>;
```

## Acceptance criteria

- Function is implemented and well commented.
- Associated unit tests (nominal and failure) are implemented and passing.

## Resources

- [multicall function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/utils/BasicMulticall.sol#L14)

**Comment by 0xTitan** [comment]
Hello, if it's still available can i work on this one please ?
Thx
