### ISSUE TITLE
Feat: Implement the functions in the `Calc` library.

### ISSUE THREAD

**Issue by Sk8erboi84** [keep-starknet-strange/satoru#239]
## Description

Implement the internal `roundup_division` function in the `Calc` library.

File: `src/utils/calc.cairo`.

Function signature:
```rust
    /// Calculates the result of dividing the first number by the second number
    /// rounded up to the nearest integer. 
    /// # Arguments
    /// * `a` - the dividend.
    /// * `b` - the divisor.
    /// # Returns
    /// The result of dividing the first number by the second number, rounded up to the nearest integer.
    fn roundup_division(a: u128, b: u128) -> u128;
```
---
Implement the internal `roundup_magnitude_division` function in the `Calc` library.

File: `src/utils/calc.cairo`.

Function signature:
```rust
    /// Calculates the result of dividing the first number by the second number,
    /// rounded up to the nearest integer.
    /// The rounding is purely on the magnitude of a, if a is negative the result
    /// is a larger magnitude negative 
    /// # Arguments
    /// * `a` - the dividend.
    /// * `b` - the divisor.
    /// # Returns
    /// The result of dividing the first number by the second number, rounded up to the nearest integer.
    fn roundup_magnitude_division(a: i128, b: u128) -> i128;
```
---
Implement the internal `sum_return_uint_128` function in the `Calc` library.

File: `src/utils/calc.cairo`.

Function signature:
```rust
    /// Adds two numbers together and return an u256 value, treating the second number as a signed integer,
    /// # Arguments
    /// * `a` - first number.
    /// * `b` - second number.
    /// # Returns
    /// the result of adding the two numbers together.
    fn sum_return_uint_128(a: u128, b: i128) -> u128;
```
---
Implement the internal `sum_return_uint_128` function in the `Calc` library.

File: `src/utils/calc.cairo`.

Function signature:
```rust
    /// Adds two numbers together and return an u256 value, treating the second number as a signed integer,
    /// # Arguments
    /// * `a` - first number.
    /// * `b` - second number.
    /// # Returns
    /// the result of adding the two numbers together.
    fn sum_return_uint_128(a: u128, b: i128) -> u128;
```
---
Implement the internal `diff` function in the `Calc` library.

File: `src/utils/calc.cairo`.

Function signature:
```rust
    /// Calculates the absolute difference between two numbers,
    /// # Arguments
    /// * `a` - first number.
    /// * `b` - second number.
    /// # Returns
    /// the absolute difference between the two numbers.
    fn diff(a: u128, b: u128) -> u128;
```
---
Implement the internal `bounded_add` function in the `Calc` library.

File: `src/utils/calc.cairo`.

Function signature:
```rust
    /// Adds two numbers together, the result is bounded to prevent overflows,
    /// # Arguments
    /// * `a` - first number.
    /// * `b` - second number.
    /// # Returns
    /// the result of adding the two numbers together.
    fn bounded_add(a: i128, b: i128) -> i128;
```
---
Implement the internal `bounded_sub` function in the `Calc` library.

File: `src/utils/calc.cairo`.

Function signature:
```rust
    /// Returns a - b, the result is bounded to prevent overflows,
    /// # Arguments
    /// * `a` - first number.
    /// * `b` - second number.
    /// # Returns
    /// the bounded result of a - b.
    fn bounded_sub(a: i128, b: i128) -> i128;
```
---
Implement the internal `to_signed` function in the `Calc` library.

File: `src/utils/calc.cairo`.

Function signature:
```rust
    /// Converts the given unsigned integer to a signed integer.
    /// # Arguments
    /// * `a` - first number.
    /// * `b` - second number.
    /// # Returns
    /// The signed integer.
    fn to_signed(a: u128, is_positive: bool) -> i128;
```

## Acceptance criteria

- Function is implemented and well commented.
- Associated unit tests (nominal and failure) are implemented and passing.

## Resources

- [roundUpDivision function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/utils/Calc.sol#L24)
- [roundUpMagnitudeDivision function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/utils/Calc.sol#L38)
- [sumReturnUint256 function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/utils/Calc.sol#L53)
- [sumReturnInt256 function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/utils/Calc.sol#L68)
- [diff function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/utils/Calc.sol#L79)
- [boundedAdd function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/utils/Calc.sol#L90)
- [boundedSub function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/utils/Calc.sol#L119)
- [toSigned function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/utils/Calc.sol#L149)

**Comment by gaetbout** [comment]
Can I?

**Comment by zarboq** [comment]
Assigned :rocket:

**Comment by gaetbout** [comment]
GM @zarboq,
In the gmx files, there are some i256 which don't exist atm. 
It has been changed to i128, is this correct or should I somehow create a i256?

**Comment by Sk8erboi84** [comment]
Hello @gaetbout,
You should keep it i128, we're not using 256 yet for simplicity reasons.
