### ISSUE TITLE
Feat: Implement the functions of `RoleStore` contract.

### ISSUE THREAD

**Issue by sparqet** [keep-starknet-strange/satoru#241]
## Description

Implement the `grant_role` function in the `RoleStore` contract.

File: `src/role/role_store.cairo`.

Function signature:
```rust
    /// Grants the specified role to the given account.
    /// # Arguments
    /// `account ` - The address of the account.
    /// `role_key` - The key of the role to grant.
    fn grant_role(ref self: TContractState, account: ContractAddress, role_key: felt252);
```
---

Implement the `revoke_role` function in the `RoleStore` contract.

File: `src/role/role_store.cairo`.

Function signature:
```rust
    /// Revokes the specified role from the given account.
    /// # Arguments
    /// `account ` - The address of the account.
    /// `role_key` - The key of the role to revoke.
    fn revoke_role(ref self: TContractState, account: ContractAddress, role_key: felt252);
```

---

Implement the `has_role` function in the `RoleStore` contract.

File: `src/role/role_store.cairo`.

Function signature:
```rust
    /// Returns true if the given account has the specified role.
    /// # Arguments
    /// `account ` - The address of the account.
    /// `role_key` - The key of the role to revoke.
    /// # Return
    /// True if the account has the role, false otherwise.
    fn has_role(self: @TContractState, account: ContractAddress, role_key: felt252) -> bool;
```

---

Implement the `get_role_count` function in the `RoleStore` contract.

File: `src/role/role_store.cairo`.

Function signature:
```rust
    /// Returns the number of roles stored in the contract.
    /// # Return
    /// The number of roles.
    fn get_role_count(self: @TContractState) -> u128;
```

---

Implement the `get_roles` function in the `RoleStore` contract.

File: `src/role/role_store.cairo`.

Function signature:
```rust
    /// Returns the keys of the roles stored in the contract.
    /// # Arguments
    /// `start` - The starting index of the range of roles to return.
    /// `end` - The ending index of the range of roles to return.
    /// # Return
    /// The keys of the roles.
    fn get_roles(self: @TContractState, start: u128, end: u128) -> Array<felt252>;
```

---

Implement the `get_role_member_count` function in the `RoleStore` contract.

File: `src/role/role_store.cairo`.

Function signature:
```rust
    /// Returns the number of members of the specified role.
    /// # Arguments
    /// `role_key` - The key of the role.
    /// # Return
    /// The number of members of the role.
    fn get_role_member_count(self: @TContractState, role_key: felt252) -> u128;
```

---

Implement the `get_role_members` function in the `RoleStore` contract.

File: `src/role/role_store.cairo`.

Function signature:
```rust
    /// Returns the members of the specified role.
    /// # Arguments
    /// `role_key` - The key of the role.
    /// `start` - The start index, the value for this index will be included.
    /// `end` - The end index, the value for this index will not be included.
    /// # Return
    /// The members of the role.
    fn get_role_members(self: @TContractState, role_key: felt252, start: u128, end: u128) -> Array<ContractAddress>;
```

---

Implement the internal `grant_role_internal` function in the `RoleStore` contract.

File: `src/role/role_store.cairo`.

Function signature:
```rust
    /// Grants the specified role to the given account.
    /// # Arguments
    /// `account ` - The address of the account.
    /// `role_key` - The key of the role to revoke.
    fn grant_role(ref self: TContractState, account: ContractAddress, role_key: felt252);
```

---

Implement the internal `revoke_role_internal` function in the `RoleStore` contract.

File: `src/role/role_store.cairo`.

Function signature:
```rust
    /// Revokes the specified role from the given account.
    /// # Arguments
    /// `account ` - The address of the account.
    /// `role_key` - The key of the role to revoke.
    fn revoke_role(ref self: TContractState, account: ContractAddress, role_key: felt252);
```

## Acceptance criteria

- Function is implemented and well commented.
- Associated unit tests (nominal and failure) are implemented and passing.

## Resources

- [grantRole function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/role/RoleStore.sol#L44)
- [revokeRole function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/role/RoleStore.sol#L54)
- [hasRole function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/role/RoleStore.sol#L65)
- [getRoleCount function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/role/RoleStore.sol#L74)
- [getRoles function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/role/RoleStore.sol#L85)
- [getRoleMemberCount function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/role/RoleStore.sol#L95)
- [getRoleMembers function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/role/RoleStore.sol#L107)
- [_grantRole function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/role/RoleStore.sol#L111)
- [_revokeRole function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/role/RoleStore.sol#L117)

**Comment by axelizsak** [comment]
Can I take this @sparqet @zarboq @Sk8erboi84 ?

**Comment by Sk8erboi84** [comment]
Yes you can ! 🚀
