### ISSUE TITLE
Feat: Create `EnumerableSet` implementation

### ISSUE THREAD

**Issue by zarboq** [keep-starknet-strange/satoru#242]
# Description

`EnumerableSet` is used in many places in GMX code but its implementation is not available yet in Cairo. We should have our own implementation of it.

Solidity implementation: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/structs/EnumerableSet.sol

**Comment by parketh** [comment]
Can I take this as a first issue?
