### ISSUE TITLE
Feat: Implement the functions in the `Precision` library.

### ISSUE THREAD

**Issue by Sk8erboi84** [keep-starknet-strange/satoru#243]
## Description

Implement the internal `apply_factor_u128` function in the `Precision` library.

File: `src/utils/precision.cairo`.

Function signature:
```rust
    /// Applies the given factor to the given value and returns the result.
    /// # Arguments
    /// * `value` - The value to apply the factor to.
    /// * `factor` - The factor to apply.
    /// # Returns
    /// The result of applying the factor to the value.
    fn apply_factor_u128(value: u128, factor: u128) -> u128;
```
---
Implement the internal `apply_factor_i128` function in the `Precision` library.

File: `src/utils/precision.cairo`.

Function signature:
```rust
    /// Applies the given factor to the given value and returns the result.
    /// # Arguments
    /// * `value` - The value to apply the factor to.
    /// * `factor` - The factor to apply.
    /// # Returns
    /// The result of applying the factor to the value.
    fn apply_factor_i128(value: u128, factor: i128) -> i128;
```
---
Implement the internal `apply_factor_roundup_magnitude` function in the `Precision` library.

File: `src/utils/precision.cairo`.

Function signature:
```rust
    /// Applies the given factor to the given value and returns the result.
    /// # Arguments
    /// * `value` - The value to apply the factor to.
    /// * `factor` - The factor to apply.
    /// # Returns
    /// The result of applying the factor to the value.
    fn apply_factor_roundup_magnitude(value: u128, factor: i128, roundup_magnitude: bool) -> i128;
```
---
Implement the internal `mul_div` function in the `Precision` library.

File: `src/utils/precision.cairo`.

Function signature:
```rust
fn mul_div(value: u128, numerator: u128, denominator: u128) -> u128;
```
---
Implement the internal `mul_div_ival` function in the `Precision` library.

File: `src/utils/precision.cairo`.

Function signature:
```rust
fn mul_div_ival(value: i128, numerator: u128, denominator: u128) -> i128;
```
---
Implement the internal `mul_div_inum` function in the `Precision` library.

File: `src/utils/precision.cairo`.

Function signature:
```rust
fn mul_div_inum(value: u128, numerator: i128, denominator: u128) -> i128;
```
---
Implement the internal `mul_div_inum_roundup` function in the `Precision` library.

File: `src/utils/precision.cairo`.

Function signature:
```rust
fn mul_div_inum_roundup(value: u128, numerator: i128, denominator: u128, roundup_magnitude: bool) -> i128;
```
---
Implement the internal `mul_div_roundup` function in the `Precision` library.

File: `src/utils/precision.cairo`.

Function signature:
```rust
fn mul_div_roundup(value: u128, numerator: u128, denominator: u128, roundup_magnitude: bool) -> u128;
```
---
Implement the internal `apply_exponent_factor` function in the `Precision` library.

File: `src/utils/precision.cairo`.

Function signature:
```rust
fn apply_exponent_factor(float_value: u128, exponent_factor: u128) -> u128;
```
---
Implement the internal `to_factor_roundup` function in the `Precision` library.

File: `src/utils/precision.cairo`.

Function signature:
```rust
fn to_factor_roundup(value: u128, divisor: u128, roundup_magnitude: bool) -> u128;
```
---
Implement the internal `to_factor` function in the `Precision` library.

File: `src/utils/precision.cairo`.

Function signature:
```rust
fn to_factor(value: u128, divisor: u128) -> u128;
```
---
Implement the internal `to_factor_ival` function in the `Precision` library.

File: `src/utils/precision.cairo`.

Function signature:
```rust
fn to_factor_ival(value: i128, divisor: u128) -> i128;
```
---
Implement the internal `float_to_wei` function in the `Precision` library.

File: `src/utils/precision.cairo`.

Function signature:
```rust
fn float_to_wei(value: u128) -> u128;
```
---
Implement the internal `wei_to_float` function in the `Precision` library.

File: `src/utils/precision.cairo`.

Function signature:
```rust
fn wei_to_float(value: u128) -> u128;
```
---
Implement the internal `basis_point_to_float` function in the `Precision` library.

File: `src/utils/precision.cairo`.

Function signature:
```rust
fn basis_points_to_float(basis_point: u128) -> u128;
```

## Acceptance criteria

- Function is implemented and well commented.
- Associated unit tests (nominal and failure) are implemented and passing.

## Resources

- [applyFactor function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/utils/Precision.sol#L40)
- [applyFactor function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/utils/Precision.sol#L51)
- [applyFactor function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/utils/Precision.sol#L55)
- [mulDiv function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/utils/Precision.sol#L59)
- [mulDiv function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/utils/Precision.sol#L63)
- [mulDiv function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/utils/Precision.sol#L67)
- [mulDiv function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/utils/Precision.sol#L72)
- [mulDiv function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/utils/Precision.sol#L77)
- [applyExponentFactor function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/utils/Precision.sol#L85)
- [toFactor function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/utils/Precision.sol#L108)
- [toFactor function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/utils/Precision.sol#L118)
- [toFactor function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/utils/Precision.sol#L122)
- [floatToWei function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/utils/Precision.sol#L133)
- [weiToFloat function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/utils/Precision.sol#L143)
- [basisPointsToFloat function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/utils/Precision.sol#L153)

**Comment by betacodd** [comment]
Can I take this one?

**Comment by Sk8erboi84** [comment]
Of course! Assigned 🚀

**Comment by Sk8erboi84** [comment]
I changed the name of the function for the last function 
```
basis_points_to_float
```
