### ISSUE TITLE
Feat: Implement the functions in the `GlobalReentrancyGuard` library.

### ISSUE THREAD

**Issue by Sk8erboi84** [keep-starknet-strange/satoru#244]
## Description

Implement the internal `non_reentrant_before` function in the `GlobalReentrancyGuard` library.

File: `src/utils/global_reentrancy_guard.cairo`.

Function signature:
```rust
    /// Modifier to avoid reentrancy.
    fn non_reentrant_before(data_store: IDataStoreDispatcher);
```
---
Implement the internal `non_reentrant_after` function in the `GlobalReentrancyGuard` library.

File: `src/utils/global_reentrancy_guard.cairo`.

Function signature:
```rust
    /// Modifier to avoid reentrancy.
    fn non_reentrant_after(data_store: IDataStoreDispatcher);
```

## Acceptance criteria

- Function is implemented and well commented.
- Associated unit tests (nominal and failure) are implemented and passing.

## Resources

- [_nonReentrantBefore function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/utils/GlobalReentrancyGuard.sol#L29)
- [_nonReentrantAfter function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/utils/GlobalReentrancyGuard.sol#L37)

**Comment by ermvrs** [comment]
https://github.com/keep-starknet-strange/satoru/pull/253
