### ISSUE TITLE
Feat: Implement the functions of `RoleModule` contract.

### ISSUE THREAD

**Issue by sparqet** [keep-starknet-strange/satoru#245]
## Description

Implement the `only_self` function in the `RoleModule` contract.

File: `src/role/role_module.cairo`.

Function signature:
```rust
    /// Only allows the contract's own address to call the function.
    fn only_self();
```

---

Implement the `only_timelock_multisig` function in the `RoleModule` contract.

File: `src/role/role_module.cairo`.

Function signature:
```rust
    /// Only allows addresses with the TIMELOCK_MULTISIG role to call the function.
    fn only_timelock_multisig();
```

---

Implement the `only_timelock_admin` function in the `RoleModule` contract.

File: `src/role/role_module.cairo`.

Function signature:
```rust
    /// Only allows addresses with the TIMELOCK_ADMIN role to call the function.
    fn only_timelock_admin();
```

---

Implement the `only_config_keeper` function in the `RoleModule` contract.

File: `src/role/role_module.cairo`.

Function signature:
```rust
    /// Only allows addresses with the CONFIG_KEEPER role to call the function.
    fn only_config_keeper();
```

Implement the `only_controller` function in the `RoleModule` contract.

File: `src/role/role_module.cairo`.

Function signature:
```rust
    /// Only allows addresses with the TIMELOCK_ADMIN role to call the function.
    fn only_controller();
```

---

Implement the `only_router_plugin` function in the `RoleModule` contract.

File: `src/role/role_module.cairo`.

Function signature:
```rust
    /// Only allows addresses with the ROUTER_PLUGIN role to call the function.
    fn only_router_plugin();
```

---

Implement the `only_market_keeper` function in the `RoleModule` contract.

File: `src/role/role_module.cairo`.

Function signature:
```rust
    /// Only allows addresses with the MARKET_KEEPER role to call the function.
    fn only_market_keeper();
```

---

Implement the `only_fee_keeper` function in the `RoleModule` contract.

File: `src/role/role_module.cairo`.

Function signature:
```rust
    /// Only allows addresses with the FEE_KEEPER role to call the function.
    fn only_fee_keeper();
```

---

Implement the `only_order_keeper` function in the `RoleModule` contract.

File: `src/role/role_module.cairo`.

Function signature:
```rust
    /// Only allows addresses with the ORDER_KEEPER role to call the function.
    fn only_order_keeper();
```

---

Implement the `only_pricing_keeper` function in the `RoleModule` contract.

File: `src/role/role_module.cairo`.

Function signature:
```rust
    /// Only allows addresses with the PRICING_KEEPER role to call the function.
    fn only_pricing_keeper();
```

---

Implement the `only_liquidation_keeper` function in the `RoleModule` contract.

File: `src/role/role_module.cairo`.

Function signature:
```rust
    /// Only allows addresses with the LIQUIDATION_KEEPER role to call the function.
    fn only_liquidation_keeper();
```

---

Implement the `only_adl_keeper` function in the `RoleModule` contract.

File: `src/role/role_module.cairo`.

Function signature:
```rust
    /// Only allows addresses with the ADL_KEEPER role to call the function.
    fn only_adl_keeper();
```

## Acceptance criteria

- Function is implemented and well commented.
- Associated unit tests (nominal and failure) are implemented and passing.

## Resources

- [onlySelf function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/role/RoleModule.sol#L26)
- [onlyTimelockMultisig function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/role/RoleModule.sol#L36)
- [onlyTimelockAdmin function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/role/RoleModule.sol#L44)
- [onlyConfigKeeper function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/role/RoleModule.sol#L52)
- [onlyController function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/role/RoleModule.sol#L60)
- [onlyRouterPlugin function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/role/RoleModule.sol#L68)
- [onlyMarketKeeper function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/role/RoleModule.sol#L76)
- [onlyFeeKeeper function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/role/RoleModule.sol#L84)
- [onlyOrderKeeper function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/role/RoleModule.sol#L92)
- [onlyPricingKeeper function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/role/RoleModule.sol#L100)
- [onlyLiquidationKeeper function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/role/RoleModule.sol#L108)
- [onlyAdlKeeper function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/role/RoleModule.sol#L116)

**Comment by danilowhk** [comment]
I can take this one

**Comment by Sk8erboi84** [comment]
Sure, I'll assign it to you 🚀
