### ISSUE TITLE
Feat: Implement the functions in the `ValidateAccount` library.

### ISSUE THREAD

**Issue by Sk8erboi84** [keep-starknet-strange/satoru#247]
## Description

Implement the internal `validate_account` function in the `AccountUtils` library.

File: `src/utils/validate_account.cairo`.

Function signature:
```rust
    /// Validates an account.
    /// # Arguments
    /// `account` - Account to validate.
    fn validate_account(account: ContractAddress);
```
---
Implement the internal `validate_receiver` function in the `ValidateAccount` library.

File: `src/utils/validate_account.cairo`.

Function signature:
```rust
    /// Validates a receiver.
    /// # Arguments
    /// * `receiver` - Account to validate.
    fn validate_receiver(receiver: ContractAddress);
```

## Acceptance criteria

- Function is implemented and well commented.
- Associated unit tests (nominal and failure) are implemented and passing.

## Resources

- [validateAccount function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/utils/AccountUtils.sol#L8)
- [validateReceiver function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/utils/AccountUtils.sol#L14)

**Comment by delaaxe** [comment]
i can do this one

**Comment by Sk8erboi84** [comment]
Assigned 🔥
