### ISSUE TITLE
Feat: Implement the functions in the `FeatureUtils` library.

### ISSUE THREAD

**Issue by Sk8erboi84** [keep-starknet-strange/satoru#248]
## Description

Implement the internal `is_feature_disabled` function in the `FeatureUtils` library.

File: `src/feature/feature_utils.cairo`.

Function signature:
```rust
    /// Get whether a feature is disabled.
    /// # Arguments
    /// * `data_store` - The data storage contract dispatcher.
    /// * `key` - The feature key.
    /// # Returns
    /// Whether the feature is disabled.
    fn is_feature_disabled(
        data_store: IDataStoreSafeDispatcher, key: felt252
    ) -> bool;
```
---
Implement the internal `validate_feature` function in the `FeatureUtils` library.

File: `src/feature/feature_utils.cairo`.

Function signature:
```rust
    /// Validate whether a feature is enabled, reverts if the feature is disabled.
    /// # Arguments
    /// * `data_store` - The data storage contract dispatcher.
    /// * `key` - The feature key.
    fn validate_feature(
        data_store: IDataStoreSafeDispatcher, key: felt252
    );
```

## Acceptance criteria

- Function is implemented and well commented.
- Associated unit tests (nominal and failure) are implemented and passing.

## Resources

- [isFeatureDisabled function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/feature/FeatureUtils.sol#L21)
- [validateFeature function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/feature/FeatureUtils.sol#L28)

**Comment by ermvrs** [comment]
Can I get this issue?

**Comment by sparqet** [comment]
Of course ! Assigned 👍

**Comment by sparqet** [comment]
> Can I get this issue?

Of course ! Assigned 👍

**Comment by ermvrs** [comment]
Does it has to revert if feature is not exist? I mean what should function return if that key never added into data store?

**Comment by zarboq** [comment]
Close #266
