### ISSUE TITLE
Feat: Implement the functions in the `NonceUtils` library.

### ISSUE THREAD

**Issue by sparqet** [keep-starknet-strange/satoru#249]
## Description

Implement the internal `get_current_nonce` function in the `NonceUtils` library.

File: `src/nonce/nonce_utils.cairo`.

Function signature:
```rust
    /// Get the current nonce value.
    /// # Arguments/
    /// * `data_store` - DataStore.
    /// # Returns
    /// Return the current nonce value.
    fn get_current_nonce(data_store: IDataStoreSafeDispatcher) -> u128;
```

---

Implement the internal `increment_nonce` function in the `NonceUtils` library.

File: `src/nonce/nonce_utils.cairo`.

Function signature:
```rust
    /// Increment the current nonce value.
    /// # Arguments/
    /// * `data_store` - DataStore.
    /// # Returns
    /// Return the new nonce value.
    fn increment_nonce(data_store: IDataStoreSafeDispatcher) -> u128;
```

---

Implement the internal `get_next_key` function in the `NonceUtils` library.

File: `src/nonce/nonce_utils.cairo`.

Function signature:
```rust
    /// Creates a felt252 hash using the next nonce. The nonce can also be used directly as a key,
    /// but for positions,a felt252 key derived from a hash of the position values is used instead.
    /// # Arguments/
    /// * `data_store` - DataStore.
    /// # Return
    /// Return felt252 hash using the next nonce value.
    fn get_next_key(data_store: IDataStoreSafeDispatcher) -> felt252;
```

## Acceptance criteria

- Function is implemented and well commented.
- Associated unit tests (nominal and failure) are implemented and passing.

## Resources

- [getCurrentNonce function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/nonce/NonceUtils.sol#L13)
- [incrementNonce function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/nonce/NonceUtils.sol#L20)
- [get_next_key function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/nonce/NonceUtils.sol#L31)

**Comment by delaaxe** [comment]
could also do this one

**Comment by Sk8erboi84** [comment]
Sure, assigned 🔥
