### ISSUE TITLE
Feat: Implement the functions in the `AdlUtils` library.

### ISSUE THREAD

**Issue by sparqet** [keep-starknet-strange/satoru#250]
## Description

Implement `update_adl_state` function in the `AdlUtils` library.

File: `src/utils/adl_utils.cairo`.

Function signature:
```rust
    ///Multiple positions may need to be reduced to ensure that the pending
    /// profits does not exceed the allowed thresholds
    /// This automatic reduction of positions can only be done if the pool is in a state
    /// where auto-deleveraging is required
    ///
    /// This function checks the pending profit state and updates an isAdlEnabled
    /// flag to avoid having to repeatedly validate whether auto-deleveraging is required
    /// Once the pending profit has been reduced below the threshold this function can
    /// be called again to clear the flag
    /// The ADL check would be possible to do in AdlHandler.executeAdl as well
    /// but with that order keepers could use stale oracle prices to prove that
    /// an ADL state is possible
    /// Having this function allows any order keeper to disable ADL if prices
    /// have updated such that ADL is no longer needed
    /// # Arguments
    /// * `data_store` - The `DataStore` contract dispatcher.
    /// * `event_emitter` - The `EventEmitter` contract dispatcher.
    /// * `oracle` - The `Oracle` contract dispatcher.
    /// * `market` - Address of the market to check.
    /// * `is_long` - Indicates whether to check the long or short side of the market.
    /// * `max_oracle_block_numbers` - The oracle block numbers for the prices stored in the oracle.
    /// # Returns
    /// Return felt252 hash using the next nonce value
    fn update_adl_state(
        data_store: IDataStoreSafeDispatcher,
        event_emitter: IEventEmitterSafeDispatcher,
        oracle: felt252,
        market: ContractAddress,
        is_long: bool,
        max_oracle_block_numbers: Span<u128>
    );
```

---

Implement `create_adl_order` function in the `AdlUtils` library.

File: `src/utils/adl_utils.cairo`.

Function signature:
```rust
    ///Construct an ADL order, a decrease order is used to reduce a profitable position.
    /// # Arguments
    /// * `CreateAdlOrderParams` - The struct.
    /// # Returns
    /// Return the key of the created order.
    fn create_adl_order(params: CreateAdlOrderParams) -> (felt252);
```

---

Implement `validate_adl` function in the `AdlUtils` library.

File: `src/utils/adl_utils.cairo`.

Function signature:
```rust
    ///Validate if the requested ADL can be executed
    /// # Arguments
    ///  * `data_store` - The `DataStore` contract dispatcher.
    /// * `market` - Address of the market to check.
    /// * `is_long` - Indicates whether to check the long or short side of the market.
    /// * `max_oracle_block_numbers` - The oracle block numbers for the prices stored in the oracle.
    /// # Returns
    /// Return the key of the created order.
    fn validate_adl(
        data_store: IDataStoreSafeDispatcher,
        market: ContractAddress,
        is_long: bool,
        max_oracle_block_numbers: Span<u128>
    );
```

---

Implement `get_latested_adl_block` function in the `AdlUtils` library.

File: `src/utils/adl_utils.cairo`.

Function signature:
```rust
    /// Get the latest block at which the ADL flag was updated
    /// # Arguments
    ///  * `data_store` - The `DataStore` contract dispatcher.
    /// * `market` - Address of the market to check.
    /// * `is_long` - Indicates whether to check the long or short side of the market.
    /// # Returns
    /// Return the latest block at which the ADL flag was updated.
    fn get_latested_adl_block(data_store: IDataStoreSafeDispatcher, market: ContractAddress, is_long: bool) -> (u128);
```

---

Implement `set_latest_adl_block` function in the `AdlUtils` library.

File: `src/utils/adl_utils.cairo`.

Function signature:
```rust
    /// Set the latest block at which the ADL flag was updated
    /// # Arguments
    ///  * `data_store` - The `DataStore` contract dispatcher.
    /// * `market` - Address of the market to check.
    /// * `is_long` - Indicates whether to check the long or short side of the market.
    /// * `value` - The value tolatest block value.
    /// # Returns
    /// Return the latest block value.
    fn set_latest_adl_block(data_store: IDataStoreSafeDispatcher, market: ContractAddress, is_long: bool, value: u128) -> (u128);
```

---

Implement `get_is_adl_enabled` function in the `AdlUtils` library.

File: `src/utils/adl_utils.cairo`.

Function signature:
```rust
    /// Get whether ADL is enabled
    /// # Arguments
    ///  * `data_store` - The `DataStore` contract dispatcher.
    /// * `market` - Address of the market to check.
    /// * `is_long` - Indicates whether to check the long or short side of the market.
    /// # Returns
    /// Return whether ADL is enabled.
    fn get_is_adl_enabled(data_store: IDataStoreSafeDispatcher, market: ContractAddress, is_long: bool) -> (bool);
```

---

Implement `set_is_adl_enabled` function in the `AdlUtils` library.

File: `src/utils/adl_utils.cairo`.

Function signature:
```rust
    /// Set whether ADL is enabled
    /// # Arguments
    ///  * `data_store` - The `DataStore` contract dispatcher.
    /// * `market` - Address of the market to check.
    /// * `is_long` - Indicates whether to check the long or short side of the market.
    /// * `value` - Whether ADL is enabled.
    /// # Returns
    /// Return whether ADL is enabled.
    fn set_is_adl_enabled(
       data_store: IDataStoreSafeDispatcher, market: ContractAddress, 
       is_long: bool, value: bool
     ) -> (bool);
```

---

Implement `emit_adl_state_updated` function in the `AdlUtils` library.

File: `src/utils/adl_utils.cairo`.

Function signature:
```rust
    /// Emit ADL state update events
    /// # Arguments
    ///  * `event_emitter` - The `EventEmitter` contract dispatcher.
    /// * `market` - Address of the market to check.
    /// * `is_long` - Indicates the ADL state update is for the long or short side of the market.
    /// * `pnt_to_pool_factor` - The ratio of PnL to pool value.
    /// * `max_pnl_factor` - The max PnL factor.
    /// * `should_enable_adl` - Whether ADL was enabled or disabled.
    fn emit_adl_state_updated(
        event_emitter: IEventEmitterSafeDispatcher,
        market: ContractAddress,
        is_long: bool,
        pnt_to_pool_factor: i128,
        max_pnl_factor: u128,
        should_enable_adl: bool
    );
```

## Acceptance criteria

- Function is implemented and well commented.
- Associated unit tests (nominal and failure) are implemented and passing.

## Resources

- [updateAdlState function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/adl/AdlUtils.sol#L87)
- [createAdlOrder function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/adl/AdlUtils.sol#L134)
- [validateAdl function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/adl/AdlUtils.sol#L207)
- [getLatestAdlBlock function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/adl/AdlUtils.sol#L231)
- [setLatestAdlBlock function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/adl/AdlUtils.sol#L243)
- [getIsAdlEnabled function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/adl/AdlUtils.sol#L254)
- [setIsAdlEnabled function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/adl/AdlUtils.sol#L266)
- [emitAdlStateUpdated function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/adl/AdlUtils.sol#L278)

**Comment by tevrat-aksoy** [comment]
Can I take this?

**Comment by sparqet** [comment]
sure ! Assigned !

**Comment by tevrat-aksoy** [comment]
Some functions and libs not implemented that are used in this lib. 
MarketUtils  doesnt have this functions.
```
        Market.Props memory _market = MarketUtils.getEnabledMarket(dataStore, market);
        MarketUtils.MarketPrices memory prices = MarketUtils.getMarketPrices(oracle, _market);
```
OrderEventUtils and EventUtils are not implemented.
Should I work on different issue until this libraries implemented?

**Comment by sparqet** [comment]
Yes, we have to wait until these libs are implemented

**Comment by sparqet** [comment]
@tevrat-aksoy can you write down the issues that's need to be done to let you finish your issue please ? 

Try to follow the same pattern as this one : https://github.com/keep-starknet-strange/satoru/issues/330#issuecomment-1711689529

**Comment by tevrat-aksoy** [comment]
following issue required for this issue:
-  #286 
- 
following functions required but not in any issue :

- [getMarketPrices function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/market/MarketUtils.sol#L194)
-  [getEnabledMarket function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/market/MarketUtils.sol#L2379)
- [isPnlFactorExceeded function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/market/MarketUtils.sol#L2484)
- [getPositionKey function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/position/PositionUtils.sol#L234C14-L234C28)
- [initItems function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/event/EventUtils.sol#L129C21-L129C21)

**Comment by tevrat-aksoy** [comment]
hey @sparqet I implemented adl_utils with some misiing libraries as you said in telegram. but I dont think I can test some functions which uses 3 - 4 missing functions. 
What should I do now?Should I leave it like this or other functions then oepn PR?
https://github.com/tevrat-aksoy/satoru/commit/4d31bbef9a0740a0f0c68f98c4867c10b9dbad2d

**Comment by sparqet** [comment]
> hey @sparqet I implemented adl_utils with some misiing libraries as you said in telegram. but I dont think I can test some functions which uses 3 - 4 missing functions. What should I do now?Should I leave it like this or test other functions then open PR? [tevrat-aksoy@4d31bbe](https://github.com/tevrat-aksoy/satoru/commit/4d31bbef9a0740a0f0c68f98c4867c10b9dbad2d)

Yes sure no problem !
