### ISSUE TITLE
Feat: Implement the function in the `Router` contract.

### ISSUE THREAD

**Issue by Sk8erboi84** [keep-starknet-strange/satoru#252]
## Description

Implement the `plugin_transfer` function in the `Router` contract.

File: `src/router/router.cairo`.

Function signature:
```rust
    /// Transfer the specified amount of tokens from the account to the receiver.
    /// # Arguments
    /// * `token` - The token address to transfer.
    /// * `account` - The account to transfer from.
    /// * `receiver` - The address of the receiver.
    /// * `amount` - The amount of tokens to transfer.
    fn plugin_transfer(
        ref self: TContractState,
        token: ContractAddress,
        account: ContractAddress,
        receiver: ContractAddress,
        amount: u128
    );
```

## Acceptance criteria

- Function is implemented and well commented.
- Associated unit tests (nominal and failure) are implemented and passing.

## Resources

- https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/router/Router.sol#L26

**Comment by zizou0x** [comment]
Hey, can I take this one please?

**Comment by Sk8erboi84** [comment]
Sure! Assigned 🔥
