### ISSUE TITLE
Feat: Implement the functions in the `liquidation_utils` library.

### ISSUE THREAD

**Issue by Sk8erboi84** [keep-starknet-strange/satoru#263]
## Description

Implement the `create_liquidation_order` function in the `liquidation_utils` library.

File: `src/liquidation/liquidation_utils.cairo`.

Function signature:
```rust
    /// Creates a liquidation order for a position.
    /// # Arguments
    /// * `data_store` - The `DataStore` contract dispatcher.
    /// * `event_emitter` - The `EventEmitter` contract dispatcher.
    /// * `account` - The position's account.
    /// * `market` - The position's market.
    /// * `collateral_token` - The position's collateralToken.
    /// * `is_long` - Whether the position is long or short.
fn create_liquidation_order(
    data_store: IDataStoreSafeDispatcher,
    event_emitter: IEventEmitterSafeDispatcher,
    account: ContractAddress,
    market: ContractAddress,
    collateral_token: ContractAddress,
    is_long: bool
) -> felt252
```

## Acceptance criteria

- Function is implemented and well commented.
- Associated unit tests (nominal and failure) are implemented and passing.

## Resources
- [createLiquidationOrder function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/liquidation/LiquidationUtils.sol#L24)

**Comment by lambda-0x** [comment]
i would like to help with this

**Comment by Sk8erboi84** [comment]
> i would like to help with this

Sure, I'll assign it for you! 🔥

**Comment by lambda-0x** [comment]
@Sk8erboi84 it seems this requires things like `position/position_utils.cairo`, `position/position_store_utils.cairo`, `order/order_store_utils.cairo` (this doesn't exist yet) to be implemented first before implementing this.

**Comment by Sk8erboi84** [comment]
> @Sk8erboi84 it seems this requires things like `position/position_utils.cairo`, `position/position_store_utils.cairo`, `order/order_store_utils.cairo` (this doesn't exist yet) to be implemented first before implementing this.

Yes, you need to wait for the other issues to be done.

**Comment by sparqet** [comment]
following issue required for this issue:
- #286
- #284
- #296
- #269 
- #249 
- PositionUtils issue

following functions required but not in any issue :
- [createLiquidationOrder function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/liquidation/LiquidationUtils.sol#L24)
