### ISSUE TITLE
Feat: Implement the function in the `deposit_handler` contract.

### ISSUE THREAD

**Issue by Sk8erboi84** [keep-starknet-strange/satoru#264]
## Description

Implement the `create_deposit` function in the `DepositHandler` contract.

File: `src/exchange/deposit_handler.cairo`.

Function signature:
```rust
    /// Creates a deposit in the deposit store.
    /// # Arguments
    /// * `account` - The depositing account.
    /// * `params` - The parameters used to create the deposit.
    /// # Returns
    /// The key of where the deposit is stored.
    fn create_deposit(
        ref self: TContractState, account: ContractAddress, params: CreateDepositParams) -> felt252;
```
---
Implement the `cancel_deposit` function in the `DepositHandler` contract.

File: `src/exchange/deposit_handler.cairo`.

Function signature:
```rust
    /// Cancels a deposit.
    /// # Arguments
    /// * `key` - The key of the deposit to cancel.
    fn cancel_deposit(ref self: TContractState, key: felt252);
```
---
Implement the `execute_deposit` function in the `DepositHandler` contract.

File: `src/exchange/deposit_handler.cairo`.

Function signature:
```rust
    /// Executes a deposit.
    /// # Arguments
    /// * `key` - The key of the deposit to execute.
    /// * `oracle_params` - The oracle params to set prices before execution.
    fn execute_deposit(ref self: TContractState, key: felt252, oracle_params: SetPricesParams);
```
---
Implement the `simulate_execute_deposit` function in the `DepositHandler` contract.

File: `src/exchange/deposit_handler.cairo`.

Function signature:
```rust
    /// Simulates execution of a deposit to check for any error.
    /// # Arguments
    /// * `key` - The key of the deposit to execute.
    /// * `oracle_params` - The oracle params to set prices before simulation.
    fn simulate_execute_deposit(ref self: TContractState, key: felt252, params: SimulatePricesParams);
```
---
Implement the `execute_deposit_keeper` function in the `DepositHandler` contract.

File: `src/exchange/deposit_handler.cairo`.

Function signature:
```rust
    /// Simulates execution of a deposit to check for any error.
    /// # Arguments
    /// * `key` - The key of the deposit to execute.
    /// * `oracle_params` - The oracle params to set prices before simulation.
    fn execute_deposit_keeper(ref self: TContractState, key: felt252, params: SimulatePricesParams);
```
---
Implement the `handle_deposit_error` function in the `DepositHandler` contract.

File: `src/exchange/deposit_handler.cairo`.

Function signature:
```rust
        /// Handles error from deposit.
        /// # Arguments
        /// * `key` - The key of the deposit to handle error for.
        /// * `starting_gas` - The starting gas of the transaction.
        /// * `reason_bytes` - The reason of the error.
        fn handle_deposit_error(ref self: ContractState, key: felt252, starting_gas: u128, reason_bytes: Array<felt252>);
```

## Acceptance criteria

- Function is implemented and well commented.
- Associated unit tests (nominal and failure) are implemented and passing.

## Resources

- [createDeposit function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/exchange/DepositHandler.sol#L48)
- [cancelDeposit function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/exchange/DepositHandler.sol#L65)
- [executeDeposit function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/exchange/DepositHandler.sol#L94)
- [simulateExecuteDeposit function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/exchange/DepositHandler.sol#L122)
- [_executeDeposit function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/exchange/DepositHandler.sol#L145)
- [getRoleMemberCount function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/exchange/DepositHandler.sol#L183)

**Comment by kasteph** [comment]
Can I give this one a shot?

**Comment by Sk8erboi84** [comment]
Sure I can assign it to you but I dont think you can complete it now 🚀

**Comment by sparqet** [comment]
following issue required for this issue:
- #267
- #245
- #248
- #320
- #297
- execute_deposit_utils
- deposit_utils

following functions required but not in any issue :
- [createDeposit function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/exchange/DepositHandler.sol#L48)
- [cancelDeposit function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/exchange/DepositHandler.sol#L65)
- [executeDeposit function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/exchange/DepositHandler.sol#L94)
- [simulateExecuteDeposit function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/exchange/DepositHandler.sol#L122)
- [_executeDeposit function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/exchange/DepositHandler.sol#L145)
- [getRoleMemberCount function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/exchange/DepositHandler.sol#L183)

**Comment by sparqet** [comment]
@kasteph can I take this one while you do execute_deposit_utils ?

**Comment by sparqet** [comment]
@kasteph  can I do this one while you do the other

**Comment by kasteph** [comment]
@sparqet yes, sounds good!
