### ISSUE TITLE
Feat: Implement the function in the `exchange_utils` library.

### ISSUE THREAD

**Issue by Sk8erboi84** [keep-starknet-strange/satoru#267]
## Description

Implement the `validate_request_cancellation` function in the `exchange_utils` library.

File: `src/exchange/exchange_utils.cairo`.

Function signature:
```rust
    /// Validates that request age is lower than request age expiration.
    /// # Arguments
    /// * `data_store` - The contract that provides access to data stored on-chain.
    /// * `created_at_block` - The block the request was created at.
    /// * `request_type` - The type of the created request.
    fn validate_request_cancellation(data_store: IDataStoreSafeDispatcher, created_at_block: u64, request_type: felt252);
```

## Acceptance criteria

- Function is implemented and well commented.
- Associated unit tests (nominal and failure) are implemented and passing.

## Resources
- [validateRequestCancellation function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/exchange/ExchangeUtils.sol#L17)

**Comment by delaaxe** [comment]
i can continue with this one

**Comment by Sk8erboi84** [comment]
Assigned 🚀
