### ISSUE TITLE
Feat: Implement the function in the `callback_utils` library.

### ISSUE THREAD

**Issue by Sk8erboi84** [keep-starknet-strange/satoru#269]
## Description

Implement the `validate_callback_gas_limit` function in the `callback_utils` library.

File: `src/callback/callback_utils.cairo`.

Function signature:
```rust
    /// Validate that the callbackGasLimit is less than the max specified value.
    /// This is to prevent callback gas limits which are larger than the max gas limits per block
    /// as this would allow for callback contracts that can consume all gas.
    /// # Arguments
    /// * `data_store` - The data store to use.
    /// * `callback_gas_limit` - The callback gas limit.
    fn validate_callback_gas_limit(
        data_store: IDataStoreSafeDispatcher, callback_gas_limit: u128
    );
```
---
Implement the `set_saved_callback_contract` function in the `callback_utils` library.

File: `src/callback/callback_utils.cairo`.

Function signature:
```rust
    /// It allows an external entity to associate a callback contract address
    /// with a specific account and market. This association is stored in a data store
    /// using the provided keys, enabling efficient retrieval for later interactions involving callbacks.
    /// # Arguments
    /// * `data_store` - The `DataStore` contract dispatcher.
    /// * `account` - The account to set callback contract for.
    /// * `market` - The market to set callback contract for.
    /// * `callback_contract` - The callback_contract address.
    fn set_saved_callback_contract(
        data_store: IDataStoreSafeDispatcher,
        account: ContractAddress,
        market: ContractAddress,
        callback_contract: ContractAddress
    );
```
---
Implement the `get_saved_callback_contract` function in the `callback_utils` library.

File: `src/callback/callback_utils.cairo`.

Function signature:
```rust
    /// It retrieves a previously stored callback contract address associated with a given account
    /// and market from the data store.
    /// # Arguments
    /// * `data_store` - The `DataStore` contract dispatcher.
    /// * `account` - The account to set callback contract for.
    /// * `market` - The market to set callback contract for.
    fn get_saved_callback_contract(
        data_store: IDataStoreSafeDispatcher, account: ContractAddress, market: ContractAddress
    ) -> ContractAddress;
```
---
Implement the `after_deposit_execution` function in the `callback_utils` library.

File: `src/callback/callback_utils.cairo`.

Function signature:
```rust
    /// Called after a deposit execution.
    /// # Arguments
    /// * `key` - They key of the deposit.
    /// * `deposit` - The deposit that was executed.
    /// * `event_data` - The event log data.
    fn after_deposit_execution(key: felt252, deposit: Deposit, event_data: EventLogData);
```
---
Implement the `after_deposit_cancellation` function in the `callback_utils` library.

File: `src/callback/callback_utils.cairo`.

Function signature:
```rust
    /// Called after a deposit cancellation.
    /// # Arguments
    /// * `key` - They key of the deposit.
    /// * `deposit` - The deposit that was cancelled.
    /// * `event_data` - The event log data.
    fn after_deposit_cancellation(key: felt252, deposit: Deposit, event_data: EventLogData);
```
---
Implement the `after_withdrawal_execution` function in the `callback_utils` library.

File: `src/callback/callback_utils.cairo`.

Function signature:
```rust
    /// Called after a withdrawal execution.
    /// # Arguments
    /// * `key` - They key of the withdrawal.
    /// * `withdrawal` - The withdrawal that was executed.
    /// * `event_data` - The event log data.
    fn after_withdrawal_execution(
        key: felt252, withdrawal: Withdrawal, event_data: EventLogData
    );
```
---
Implement the `after_withdrawal_cancellation` function in the `callback_utils` library.

File: `src/callback/callback_utils.cairo`.

Function signature:
```rust
    /// Called after an withdrawal cancellation.
    /// # Arguments
    /// * `key` - They key of the withdrawal.
    /// * `withdrawal` - The withdrawal that was cancelled.
    /// * `event_data` - The event log data.
    fn after_withdrawal_cancellation(
        key: felt252, withdrawal: Withdrawal, event_data: EventLogData
    );
```
---
Implement the `after_order_execution` function in the `callback_utils` library.

File: `src/callback/callback_utils.cairo`.

Function signature:
```rust
    /// Called after an order execution.
    /// # Arguments
    /// * `key` - They key of the order.
    /// * `order` - The order that was executed.
    /// * `event_data` - The event log data.
    fn after_order_execution(key: felt252, order: Order, event_data: EventLogData);
```
---
Implement the `after_order_cancellation` function in the `callback_utils` library.

File: `src/callback/callback_utils.cairo`.

Function signature:
```rust
    /// Called after an order cancellation.
    /// # Arguments
    /// * `key` - They key of the order.
    /// * `order` - The order that was cancelled.
    /// * `event_data` - The event log data.
    fn after_order_cancellation(key: felt252, order: Order, event_data: EventLogData);
```
---
Implement the `after_order_frozen` function in the `callback_utils` library.

File: `src/callback/callback_utils.cairo`.

Function signature:
```rust
    /// Called after an order cancellation.
    /// # Arguments
    /// * `key` - They key of the order.
    /// * `order` - The order that was frozen.
    /// * `event_data` - The event log data.
    fn after_order_frozen(key: felt252, order: Order, event_data: EventLogData);
```
---
Implement the `is_valid_callback_contract` function in the `callback_utils` library.

File: `src/callback/callback_utils.cairo`.

Function signature:
```rust
    /// Validates that the given address is a contract.
    /// # Arguments
    /// * `callback_contract` - The callback contract.
    fn is_valid_callback_contract(callback_contract: ContractAddress) -> bool;
```
---
## Acceptance criteria

- Function is implemented and well commented.
- Associated unit tests (nominal and failure) are implemented and passing.

## Resources
- [validateCallbackGasLimit function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/callback/CallbackUtils.sol#L53)
- [setSavedCallbackContract function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/callback/CallbackUtils.sol#L60)
- [getSavedCallbackContractfunction in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/callback/CallbackUtils.sol#L64)
- [afterDepositExecution function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/callback/CallbackUtils.sol#L71)
- [afterDepositCancellation function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/callback/CallbackUtils.sol#L91)
- [afterWithdrawalExecution function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/callback/CallbackUtils.sol#L111)
- [afterWithdrawalCancellation function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/callback/CallbackUtils.sol#L131)
- [afterOrderExecution function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/callback/CallbackUtils.sol#L154)
- [afterOrderCancellation function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/callback/CallbackUtils.sol#L174)
- [afterOrderFrozen function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/callback/CallbackUtils.sol#L194)
- [isValidCallbackContractfunction in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/callback/CallbackUtils.sol#L213)

**Comment by delaaxe** [comment]
I can continue with this one!

**Comment by Sk8erboi84** [comment]
Of course ! Assigned 🔥
