### ISSUE TITLE
Feat: Implement the functions in the `StrictBank` contract.

### ISSUE THREAD

**Issue by sparqet** [keep-starknet-strange/satoru#272]
## Description

Implement the `record_transfer_in` function in the `StrictBank` contract.

File: `src/bank/strict_bank.cairo`.

Function signature:
```rust
    /// Records a token transfer into the contract
    /// # Arguments
    /// * `token` - The token to record the transfer for
    /// # Return
    /// The amount of tokens transferred in
    fn record_transfer_in(token: ContractAddress) -> (u128)
```

---

Implement the `sync_token_balance` function in the `StrictBank` contract.

File: `src/bank/strict_bank.cairo`.

Function signature:
```rust
    /// this can be used to update the tokenBalances in case of token burns
    /// or similar balance changes
    /// the prevBalance is not validated to be more than the nextBalance as this
    /// could allow someone to block this call by transferring into the contract    
    /// # Arguments
    /// * `token` - The token to record the burn for
    /// # Return
    /// The new balance
    fn sync_token_balance(token: ContractAddress) -> (u128)
```

---

Implement the `record_transfer_in_internal` function in the `StrictBank` contract.

File: `src/bank/strict_bank.cairo`.

Function signature:
```rust
    /// Records a token transfer into the contract
    /// # Arguments
    /// * `token` - The token to record the transfer for
    /// # Return
    /// The amount of tokens transferred in
    fn record_transfer_in_internal(token: ContractAddress) -> (u128)
```

---

Implement the internal `after_transfer_out_infernal` function in the `StrictBank` contract.

File: `src/bank/strict_bank.cairo`.

Function signature:
```rust
    /// Transfer tokens from this contract to a receiver
    /// # Arguments
    /// * `token` - token the token to transfer
    fn after_transfer_out_infernal(token: ContractAddress)
```

## Acceptance criteria

- Function is implemented and well commented.
- Associated unit tests (nominal and failure) are implemented and passing.

## Resources
- [recordTransferIn function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/bank/StrictBank.sol#L32)
- [syncTokenBalance function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/bank/StrictBank.sol#L42)
- [_recordTransferIn function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/bank/StrictBank.sol#L51)
- [_afterTransferOut function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/bank/StrictBank.sol#L62)

**Comment by VictorONN** [comment]
Hello, can I take this? Thanks.

**Comment by Sk8erboi84** [comment]
Yes sure! Assigned 🔥

**Comment by VictorONN** [comment]
Hello, I see the transfer_out function is now implemented. I needed it. Will wrap things up on my end soon.

**Comment by sparqet** [comment]
Hi @VictorONN ! How is it going ?

**Comment by VictorONN** [comment]
Hello, can I touch base by tomorrow latest this time? I will have it ready then.
