### ISSUE TITLE
Feat: Implement the function in the `order_handler` contract.

### ISSUE THREAD

**Issue by Sk8erboi84** [keep-starknet-strange/satoru#273]
## Description

Implement the `create_order` function in the `OrderHandler` contract.

File: `src/exchange/order_handler.cairo`.

Function signature:
```rust
    /// Creates an order in the order store.
    /// # Arguments
    /// * `account` - The order's account.
    /// * `params` - The parameters used to create the order.
    /// # Returns
    /// The key of where the order is stored.
    fn create_order(
        ref self: TContractState, account: ContractAddress, params: CreateOrderParams
    ) -> felt252;
```
---
Implement the `update_order` function in the `OrderHandler` contract.

File: `src/exchange/order_handler.cairo`.

Function signature:
```rust
    /// # Arguments
    /// * `key` - The unique ID of the order to be updated.
    /// * `size_delta_usd` - The new size delta for the order.
    /// * `acceptable_price` - The new acceptable price for the order.
    /// * `trigger_price` - The new trigger price for the order.
    /// * `min_output_amount` - The minimum output amount for decrease orders and swaps.
    /// * `order` - The order to update that will be stored.
    fn update_order(
        ref self: TContractState,
        key: felt252,
        size_delta_usd: u128,
        acceptable_price: u128,
        trigger_price: u128,
        min_output_amount: u128,
        order: Order
    );
```
---
Implement the `cancel_order` function in the `OrderHandler` contract.

File: `src/exchange/order_handler.cairo`.

Function signature:
```rust
    /// Cancels the given order. The `cancelOrder()` feature must be enabled for the given order
    /// type. The caller must be the owner of the order. The order is cancelled by calling the `cancelOrder()`
    /// function in the `OrderUtils` contract. This function also records the starting gas amount and the
    /// reason for cancellation, which is passed to the `cancelOrder()` function.
    /// # Arguments
    /// * `key` - The unique ID of the order to cancel.
    fn cancel_order(ref self: TContractState, key: felt252);
```
---
Implement the `execute_order` function in the `OrderHandler` contract.

File: `src/exchange/order_handler.cairo`.

Function signature:
```rust
    /// Executes an order.
    /// # Arguments
    /// * `key` - The key of the order to execute.
    /// * `oracle_params` - The oracle params to set prices before execution.
    fn execute_order(ref self: TContractState, key: felt252, oracle_params: SetPricesParams);
```
---
Implement the `simulate_execute_order` function in the `OrderHandler` contract.

File: `src/exchange/order_handler.cairo`.

Function signature:
```rust
    /// Simulates execution of an order to check for any error.
    /// # Arguments
    /// * `key` - The key of the order to execute.
    /// * `oracle_params` - The oracle params to simulate prices.
    fn simulate_execute_order(ref self: TContractState, key: felt252, params: SimulatePricesParams);
```
---
Implement the `execute_order_keeper` function in the `OrderHandler` contract.

File: `src/exchange/order_handler.cairo`.

Function signature:
```rust
    /// Executes an order with keeper.
    /// # Arguments
    /// * `key` - The key of the order to execute.
    /// * `oracle_params` - The oracle params to set prices before execution.
    /// * `keeper` - The keeper executing the order.
    fn execute_order_keeper(
        ref self: TContractState,
        key: felt252,
        oracle_params: SetPricesParams,
        keeper: ContractAddress
    );
```
---
Implement the `handle_order_error` function in the `OrderHandler` contract.

File: `src/exchange/order_handler.cairo`.

Function signature:
```rust
        /// Handles error from order.
        /// # Arguments
        /// * `key` - The key of the deposit to handle error for.
        /// * `starting_gas` - The starting gas of the transaction.
        /// * `reason_bytes` - The reason of the error.
        fn handle_order_error(
            key: felt252, starting_gas: u128, reason_bytes: Array<felt252>
        );
```
---
Implement the `validate_state_frozen_order_keeper` function in the `OrderHandler` contract.

File: `src/exchange/order_handler.cairo`.

Function signature:
```rust
        /// Validate that the keeper is a frozen order keeper.
        /// # Arguments
        /// * `keeper` - address of the keeper.
        fn validate_state_frozen_order_keeper(keeper: ContractAddress);
```

## Acceptance criteria

- Function is implemented and well commented.
- Associated unit tests (nominal and failure) are implemented and passing.

## Resources

- [createOrder function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/exchange/OrderHandler.sol#L37)
- [updateOrder function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/exchange/OrderHandler.sol#L76)
- [cancelOrder function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/exchange/OrderHandler.sol#L122)
- [simulateExecuteOrder function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/exchange/OrderHandler.sol#L153)
- [executeOrder function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/exchange/OrderHandler.sol#L174)
- [_executeOrder function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/exchange/OrderHandler.sol#L200)
- [_handleOrderError function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/exchange/OrderHandler.sol#L232)
- [_validateFrozenOrderKeeper function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/exchange/OrderHandler.sol#L323)

**Comment by parketh** [comment]
Could I take this as a next issue?

**Comment by Sk8erboi84** [comment]
Of course you can! Assigned 🔥

**Comment by parketh** [comment]
Apologies for the delay - this should be ready for review again @zarboq

**Comment by zarboq** [comment]
#313
