### ISSUE TITLE
Feat: Implement the function in the `liquidation_handler` contract.

### ISSUE THREAD

**Issue by Sk8erboi84** [keep-starknet-strange/satoru#274]
## Description

Implement the `execute_liquidation` function in the `LiquidationHandler` contract.

File: `src/exchange/liquidation_handler.cairo`.

Function signature:
```rust
    /// Executes a position liquidation.
    /// # Arguments
    /// * `account` - The account of the position to liquidate.
    /// * `market` - The position's market.
    /// * `collateral_token` - The position's collateralToken.
    /// * `is_long` - Whether the position is long or short.
    /// * `oracle_params` - The oracle params to set prices before execution.
    fn execute_liquidation(
        ref self: TContractState,
        account: ContractAddress,
        market: ContractAddress,
        collateral_token: ContractAddress,
        is_long: bool,
        oracle_params: SetPricesParams
    );
```

## Acceptance criteria

- Function is implemented and well commented.
- Associated unit tests (nominal and failure) are implemented and passing.

## Resources

- [executeLiquidation function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/exchange/LiquidationHandler.sol#L38)

**Comment by lucienfer** [comment]
hello, can i take this one ?

**Comment by zarboq** [comment]
Letsgo !

**Comment by sparqet** [comment]
following issue required for this issue:
- BaseOrderHandler

following functions required but not in any issue :
- [executeLiquidation function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/exchange/LiquidationHandler.sol#L38)
