### ISSUE TITLE
Feat: Implement `Deposit` functions in the `DataStore` contract.

### ISSUE THREAD

**Issue by sparqet** [keep-starknet-strange/satoru#283]
## Description

Implement the `get_deposit` function in the `DataStore` contract.

File: `src/data/data_store.cairo`.

Function signature:
```rust
    fn get_deposit(
        self: @ContractState,
        key: felt252
    ) -> Option<Deposit>;
```

---

Implement the `set_deposit` function in the `DataStore` contract.

File: `src/data/data_store.cairo`.

Function signature:
```rust
    fn set_deposit(
        ref self: ContractState,
        key: felt252,
        deposit: Deposit
    );
```

---

Implement the `remove_deposit` function in the `DataStore` contract.

File: `src/data/data_store.cairo`.

Function signature:
```rust
    fn remove_deposit(
        ref self: ContractState,
        key: felt252,
        account: ContractAddress
    );
```

---

Implement the internal `get_deposit_count` function in the `DataStore` contract.

File: `src/data/data_store.cairo`.

Function signature:
```rust
    fn get_deposit_count(self: @ContractState) -> u128;
```

---

Implement the internal `get_deposit_keys` function in the `DataStore` contract.

File: `src/data/data_store.cairo`.

Function signature:
```rust
    fn get_deposit_keys(self: @ContractState, start: u128, end: u128) -> (Array<felt252>);
```

---

Implement the internal `get_account_deposit_count` function in the `DataStore` contract.

File: `src/data/data_store.cairo`.

Function signature:
```rust
    fn get_account_deposit_count(self: @ContractState, account: ContractAddress) -> (u128);
```

---

Implement the internal `get_account_deposit_keys` function in the `DataStore` contract.

File: `src/data/data_store.cairo`.

Function signature:
```rust
    fn get_account_deposit_keys(self: @ContractState, account: ContractAddress, start: u128, end: u128) -> (Array<felt252>);
```

## Acceptance criteria

- Function is implemented and well commented.
- Associated unit tests (nominal and failure) are implemented and passing.

## Resources

- [get function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/deposit/DepositStoreUtils.sol#L36)
- [set function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/deposit/DepositStoreUtils.sol#L109)
- [remove function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/deposit/DepositStoreUtils.sol#L201)
- [getDepositCount function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/deposit/DepositStoreUtils.sol#L281)
- [getDepositKeys function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/deposit/DepositStoreUtils.sol#L285)
- [getAccountDepositCount function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/deposit/DepositStoreUtils.sol#L289)
- [getAccountDepositKeys function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/deposit/DepositStoreUtils.sol#L293)

**Comment by Sk8erboi84** [comment]
Assigned 🔥
