### ISSUE TITLE
Feat: Implement `Order` functions in the `DataStore` contract.

### ISSUE THREAD

**Issue by sparqet** [keep-starknet-strange/satoru#284]
## Description

Implement the `get_order` function in the `DataStore` contract.

File: `src/data/data_store.cairo`.

Function signature:
```rust
    fn get_order(
        self: @ContractState,
        key: felt252
    ) -> Option<Order>;
```

---

Implement the `set_order` function in the `DataStore` contract.

File: `src/data/data_store.cairo`.

Function signature:
```rust
    fn set_order(
        ref self: ContractState,
        key: felt252,
        order: Order
    );
```

---

Implement the `remove_order` function in the `DataStore` contract.

File: `src/data/data_store.cairo`.

Function signature:
```rust
    fn remove_order(
        ref self: ContractState,
        key: felt252,
        account: ContractAddress
    );
```

---

Implement the internal `get_order_count` function in the `DataStore` contract.

File: `src/data/data_store.cairo`.

Function signature:
```rust
    fn get_order_count(self: @ContractState) -> u128;
```

---

Implement the internal `get_order_keys` function in the `DataStore` contract.

File: `src/data/data_store.cairo`.

Function signature:
```rust
    fn get_order_keys(self: @ContractState, start: u128, end: u128) -> Array<felt252>;
```

---

Implement the internal `get_account_order_count` function in the `DataStore` contract.

File: `src/data/data_store.cairo`.

Function signature:
```rust
    fn get_account_order_count(self: @ContractState, account: ContractAddress) -> u128;
```

---

Implement the internal `get_account_order_keys` function in the `DataStore` contract.

File: `src/data/data_store.cairo`.

Function signature:
```rust
    fn get_account_order_keys(self: @ContractState, account: ContractAddress, start: u128, end: u128) -> Array<felt252>;
```

## Acceptance criteria

- Function is implemented and well commented.
- Associated unit tests (nominal and failure) are implemented and passing.

## Resources

- [get function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/order/OrderStoreUtils.sol#L40)
- [set function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/order/OrderStoreUtils.sol#L129)
- [remove function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/order/OrderStoreUtils.sol#L241)
- [getOrderCount function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/order/OrderStoreUtils.sol#L337)
- [getOrderKeys function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/order/OrderStoreUtils.sol#L341)
- [getAccountOrderCount function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/order/OrderStoreUtils.sol#L345)
- [getAccountOrderKeys function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/order/OrderStoreUtils.sol#L349)

**Comment by tevrat-aksoy** [comment]
Can I take this?
