### ISSUE TITLE
Feat: Implement `Withdrawal` functions in the `DataStore` contract.

### ISSUE THREAD

**Issue by sparqet** [keep-starknet-strange/satoru#288]
## Description

Implement the `get_withdrawal` function in the `DataStore` contract.

File: `src/data/data_store.cairo`.

Function signature:
```rust
    fn get_withdrawal(
        self: @ContractState,
        key: felt252
    ) -> Option<Withdrawal>;
```

---

Implement the `set_withdrawal` function in the `DataStore` contract.

File: `src/data/data_store.cairo`.

Function signature:
```rust
    fn set_withdrawal(
        ref self: ContractState,
        key: felt252,
        withdrawal: Withdrawal
    );
```

---

Implement the `remove_withdrawal` function in the `DataStore` contract.

File: `src/data/data_store.cairo`.

Function signature:
```rust
    fn remove_withdrawal(
        ref self: ContractState,
        key: felt252,
        account: ContractAddress
    );
```

---

Implement the internal `get_withdrawal_count` function in the `DataStore` contract.

File: `src/data/data_store.cairo`.

Function signature:
```rust
    fn get_withdrawal_count(self: @ContractState) -> u128;
```

---

Implement the internal `get_withdrawal_keys` function in the `DataStore` contract.

File: `src/data/data_store.cairo`.

Function signature:
```rust
    fn get_withdrawal_keys(self: @ContractState, start: u128, end: u128) -> Array<felt252>;
```

---

Implement the internal `get_account_withdrawal_count` function in the `DataStore` contract.

File: `src/data/data_store.cairo`.

Function signature:
```rust
    fn get_account_withdrawal_count(self: @ContractState, account: ContractAddress) -> u128;
```

---

Implement the internal `get_account_withdrawal_keys` function in the `DataStore` contract.

File: `src/data/data_store.cairo`.

Function signature:
```rust
    fn get_account_withdrawal_keys(self: @ContractState, account: ContractAddress, start: u128, end: u128) -> Array<felt252>;
```

## Acceptance criteria

- Function is implemented and well commented.
- Associated unit tests (nominal and failure) are implemented and passing.

## Resources

- [get function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/withdrawal/WithdrawalStoreUtils.sol#L34)
- [set function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/withdrawal/WithdrawalStoreUtils.sol#L99)
- [remove function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/withdrawal/WithdrawalStoreUtils.sol#L181)
- [getWithdrawalCount function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/withdrawal/WithdrawalStoreUtils.sol#L253)
- [getWithdrawalKeys function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/withdrawal/WithdrawalStoreUtils.sol#L257)
- [getWithdrawalPositionCount function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/withdrawal/WithdrawalStoreUtils.sol#L261)
- [getAccountWithdrawalKeys function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/withdrawal/WithdrawalStoreUtils.sol#L265)

**Comment by enitrat** [comment]
I can take this one :)

**Comment by sparqet** [comment]
Of course ! Assigned 🚀

**Comment by enitrat** [comment]
Should all of these last added issues be grouped in the DataStore contract? Don't we prefer to separate them by concern?

**Comment by sparqet** [comment]
We prefer them to be grouped in the DataStore contract

**Comment by enitrat** [comment]
I think this will grow super big and eventually could benefit from being split into components once released

**Comment by abdelhamidbakhta** [comment]
> 

Agreed. 
In anycase we will do a big refactor of the tests once Starknet Foundry enables mock of contracts and reuse of deployed contracts across multiple files.
So yes when components are released we can refactor and split by business objects.
