### ISSUE TITLE
Feat: Implement the functions in the `OracleUtils` library.

### ISSUE THREAD

**Issue by Sk8erboi84** [keep-starknet-strange/satoru#290]
## Description

Implement `validate_block_number_within_range` function in the `OracleUtils` library.

File: `src/oracle/oracle_utils.cairo`.

Function signature:
```rust
/// Validates wether a block number is in range.
/// # Arguments
/// * `min_oracle_block_numbers` - The oracles block number that should be less than block_number.
/// * `max_oracle_block_numbers` - The oracles block number that should be higher than block_number.
/// * `block_number` - The block number to compare to.
fn validate_block_number_within_range(
    min_oracle_block_numbers: Array<u128>, max_oracle_block_numbers: Array<u128>, block_number: u128
);
```
---
Implement `is_block_number_within_range` function in the `OracleUtils` library.

File: `src/oracle/oracle_utils.cairo`.

Function signature:
```rust
/// Validates wether a block number is in range.
/// # Arguments
/// * `min_oracle_block_numbers` - The oracles block number that should be less than block_number.
/// * `max_oracle_block_numbers` - The oracles block number that should be higher than block_number.
/// * `block_number` - The block number to compare to.
/// # Returns
/// True if block_number is in range, false else.
fn is_block_number_within_range(
    min_oracle_block_numbers: Array<u128>, max_oracle_block_numbers: Array<u128>, block_number: u128
) -> bool;
```
---
Implement `get_uncompacted_price` function in the `OracleUtils` library.

File: `src/oracle/oracle_utils.cairo`.

Function signature:
```rust
/// Get the uncompacted price at the specified index.
/// # Arguments
/// * `compacted_prices` - The compacted prices.
/// * `index` - The index to get the decimal at.
/// # Returns
/// The price at the specified index.
fn get_uncompacted_price(compacted_prices: Array<u128>, index: u128) -> u128;
```
---
Implement `get_uncompacted_decimal` function in the `OracleUtils` library.

File: `src/oracle/oracle_utils.cairo`.

Function signature:
```rust
/// Get the uncompacted decimal at the specified index.
/// # Arguments
/// * `compacted_decimals` - The compacted decimals.
/// * `index` - The index to get the decimal at.
/// # Returns
/// The decimal at the specified index.
fn get_uncompacted_decimal(compacted_decimals: Array<u128>, index: u128) -> u128;
```
---
Implement `get_uncompacted_price_index` function in the `OracleUtils` library.

File: `src/oracle/oracle_utils.cairo`.

Function signature:
```rust
/// Get the uncompacted price index at the specified index.
/// # Arguments
/// * `compacted_price_indexes` - The compacted indexes.
/// * `index` - The index to get the price index at.
/// # Returns
/// The uncompacted price index at the specified index.
fn get_uncompacted_price_index(compacted_price_indexes: Array<u128>, index: u128) -> u128;
```
---
Implement `get_uncompacted_oracle_block_numbers` function in the `OracleUtils` library.

File: `src/oracle/oracle_utils.cairo`.

Function signature:
```rust
/// Get the uncompacted oracle block numbers.
/// # Arguments
/// * `compacted_oracle_block_numbers` - The compacted oracle block numbers.
/// * `length` - The length of the uncompacted oracle block numbers.
/// # Returns
/// The uncompacted oracle block numbers.
fn get_uncompacted_oracle_block_numbers(
    compacted_oracle_block_numbers: Array<u128>, length: u128
) -> Array<u128>;
```
---
Implement `get_uncompacted_oracle_block_number` function in the `OracleUtils` library.

File: `src/oracle/oracle_utils.cairo`.

Function signature:
```rust
/// Get the uncompacted oracle block number.
/// # Arguments
/// * `compacted_oracle_block_numbers` - The compacted oracle block numbers.
/// * `index` - The index to get the uncompacted oracle block number at.
/// # Returns
/// The uncompacted oracle block number.
fn get_uncompacted_oracle_block_number(
    compacted_oracle_block_numbers: Array<u128>, index: u128
) -> u128;
```
---
Implement `get_uncompacted_oracle_timestamp` function in the `OracleUtils` library.

File: `src/oracle/oracle_utils.cairo`.

Function signature:
```rust
/// Get the uncompacted oracle timestamp.
/// # Arguments
/// * `compacted_oracle_timestamps` - The compacted oracle timestamps.
/// * `index` - The index to get the uncompacted oracle timestamp at.
/// # Returns
/// The uncompacted oracle timestamp.
fn get_uncompacted_oracle_timestamp(compacted_oracle_timestamps: Array<u128>, index: u128) -> u128;
```
---
Implement `validate_signer` function in the `OracleUtils` library.

File: `src/oracle/oracle_utils.cairo`.

Function signature:
```rust
fn validate_signer(
    salt: felt252, info: ReportInfo, signature: Array<felt252>, expected_signer: ContractAddress
);
```
---
Implement `revert_oracle_block_number_not_within_range` function in the `OracleUtils` library.

File: `src/oracle/oracle_utils.cairo`.

Function signature:
```rust
/// Revert with OracleBlockNumberNotWithinRange error.
/// # Arguments
/// * `max_oracle_block_number` - The max block number used for the signed message hash.
/// * `block` - The current block number.
fn revert_oracle_block_number_not_within_range(
    min_oracle_block_numbers: Array<u128>, max_oracle_block_numbers: Array<u128>, block_number: u64
);
```
---
Implement `is_oracle_error` function in the `OracleUtils` library.

File: `src/oracle/oracle_utils.cairo`.

Function signature:
```rust
/// Check wether `error` is an OracleError.
/// # Arguments
/// * `error` - The error to check.
/// # Returns
/// Wether it's the right error.
fn is_oracle_error(error_selector: felt252) -> bool;
```
---
Implement `is_empty_price_error` function in the `OracleUtils` library.

File: `src/oracle/oracle_utils.cairo`.

Function signature:
```rust
/// Check wether `error` is an EmptyPriceError.
/// # Arguments
/// * `error` - The error to check.
/// # Returns
/// Wether it's the right error.
fn is_empty_price_error(error_selector: felt252) -> bool;
```
---
Implement `is_oracle_block_number_error` function in the `OracleUtils` library.

File: `src/oracle/oracle_utils.cairo`.

Function signature:
```rust
/// Check wether `error` is an OracleBlockNumberError.
/// # Arguments
/// * `error` - The error to check.
/// # Returns
/// Wether it's the right error.
fn is_oracle_block_number_error(error_selector: felt252) -> bool;
```
---
## Acceptance criteria

- Function is implemented and well commented.
- Associated unit tests (nominal and failure) are implemented and passing.

## Resources

- [validateBlockNumberWithinRange function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/oracle/OracleUtils.sol#L82)
- [isBlockNumberWithinRange function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/oracle/OracleUtils.sol#L100)
- [getUncompactedPrice function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/oracle/OracleUtils.sol#L120)
- [getUncompactedDecimal function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/oracle/OracleUtils.sol#L138)
- [getUncompactedPriceIndex function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/oracle/OracleUtils.sol#L155)
- [getUncompactedOracleBlockNumbers function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/oracle/OracleUtils.sol#L172)
- [getUncompactedOracleBlockNumber function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/oracle/OracleUtils.sol#L186)
- [getUncompactedOracleTimestamp function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/oracle/OracleUtils.sol#L204)
- [validateSigner function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/oracle/OracleUtils.sol#L231)
- [revertOracleBlockNumberNotWithinRange function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/oracle/OracleUtils.sol#L258)
- [isOracleError function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/oracle/OracleUtils.sol#L266)
- [isEmptyPriceError function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/oracle/OracleUtils.sol#L278)
- [isOracleBlockNumberError function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/oracle/OracleUtils.sol#L286)

**Comment by sparqet** [comment]
> I will take this one 🫡

Of course ! Assigned 🔥

**Comment by Cevedale** [comment]
**Issue Description:**
Implement several functions in the OracleUtils library to enhance its functionality and provide associated unit tests. 

**Function 1: validate_block_number_within_range**
```rust
/// Validates whether a block number is within the specified range.
/// # Arguments
/// * `min_oracle_block_numbers` - The minimum oracle block numbers allowed.
/// * `max_oracle_block_numbers` - The maximum oracle block numbers allowed.
/// * `block_number` - The block number to compare.
fn validate_block_number_within_range(
    min_oracle_block_numbers: Array<u128>,
    max_oracle_block_numbers: Array<u128>,
    block_number: u128,
) {
    // Implement the logic to validate the block number here
}

/// Unit Test
#[test]
fn test_validate_block_number_within_range() {
    let min_oracle_block_numbers = [1, 2, 3];
    let max_oracle_block_numbers = [10, 20, 30];
    let block_number = 15;
    
    assert!(validate_block_number_within_range(min_oracle_block_numbers, max_oracle_block_numbers, block_number));
}
```

**Function 2: is_block_number_within_range**
```rust
/// Validates whether a block number is within the specified range.
/// # Arguments
/// * `min_oracle_block_numbers` - The minimum oracle block numbers allowed.
/// * `max_oracle_block_numbers` - The maximum oracle block numbers allowed.
/// * `block_number` - The block number to compare.
/// # Returns
/// True if block_number is in range, false otherwise.
fn is_block_number_within_range(
    min_oracle_block_numbers: Array<u128>,
    max_oracle_block_numbers: Array<u128>,
    block_number: u128,
) -> bool {
    // Implement the logic to check if the block number is within the range
    // Return true if it is, false otherwise
}
```

**Function 3: get_uncompacted_price**
```rust
/// Get the uncompacted price at the specified index.
/// # Arguments
/// * `compacted_prices` - The compacted prices.
/// * `index` - The index to get the decimal at.
/// # Returns
/// The price at the specified index.
fn get_uncompacted_price(compacted_prices: Array<u128>, index: u128) -> u128 {
    // Implement the logic to retrieve the uncompacted price
}
```

**Function 4: get_uncompacted_decimal**
```rust
/// Get the uncompacted decimal at the specified index.
/// # Arguments
/// * `compacted_decimals` - The compacted decimals.
/// * `index` - The index to get the decimal at.
/// # Returns
/// The decimal at the specified index.
fn get_uncompacted_decimal(compacted_decimals: Array<u128>, index: u128) -> u128 {
    // Implement the logic to retrieve the uncompacted decimal
}
```

The other functions can be implemented in a similar fashion, following the provided signatures. Make sure to write appropriate unit tests for each function to ensure their correctness.

**Comment by Cevedale** [comment]
**Issue Description:**
Implement several functions in the OracleUtils library to enhance its functionality and provide associated unit tests. 

**Function 1: validate_block_number_within_range**
```rust
/// Validates whether a block number is within the specified range.
/// # Arguments
/// * `min_oracle_block_numbers` - The minimum oracle block numbers allowed.
/// * `max_oracle_block_numbers` - The maximum oracle block numbers allowed.
/// * `block_number` - The block number to compare.
fn validate_block_number_within_range(
    min_oracle_block_numbers: Array<u128>,
    max_oracle_block_numbers: Array<u128>,
    block_number: u128,
) {
    // Implement the logic to validate the block number here
}

/// Unit Test
#[test]
fn test_validate_block_number_within_range() {
    let min_oracle_block_numbers = [1, 2, 3];
    let max_oracle_block_numbers = [10, 20, 30];
    let block_number = 15;
    
    assert!(validate_block_number_within_range(min_oracle_block_numbers, max_oracle_block_numbers, block_number));
}
```

**Function 2: is_block_number_within_range**
```rust
/// Validates whether a block number is within the specified range.
/// # Arguments
/// * `min_oracle_block_numbers` - The minimum oracle block numbers allowed.
/// * `max_oracle_block_numbers` - The maximum oracle block numbers allowed.
/// * `block_number` - The block number to compare.
/// # Returns
/// True if block_number is in range, false otherwise.
fn is_block_number_within_range(
    min_oracle_block_numbers: Array<u128>,
    max_oracle_block_numbers: Array<u128>,
    block_number: u128,
) -> bool {
    // Implement the logic to check if the block number is within the range
    // Return true if it is, false otherwise
}
```

**Function 3: get_uncompacted_price**
```rust
/// Get the uncompacted price at the specified index.
/// # Arguments
/// * `compacted_prices` - The compacted prices.
/// * `index` - The index to get the decimal at.
/// # Returns
/// The price at the specified index.
fn get_uncompacted_price(compacted_prices: Array<u128>, index: u128) -> u128 {
    // Implement the logic to retrieve the uncompacted price
}
```

**Function 4: get_uncompacted_decimal**
```rust
/// Get the uncompacted decimal at the specified index.
/// # Arguments
/// * `compacted_decimals` - The compacted decimals.
/// * `index` - The index to get the decimal at.
/// # Returns
/// The decimal at the specified index.
fn get_uncompacted_decimal(compacted_decimals: Array<u128>, index: u128) -> u128 {
    // Implement the logic to retrieve the uncompacted decimal
}
```

**Comment by Sk8erboi84** [comment]
@Cevedale I dont understand what do you mean.
