### ISSUE TITLE
Feat: Implement `OrderEvents` functions in the `EventEmitter` contract.

### ISSUE THREAD

**Issue by sparqet** [keep-starknet-strange/satoru#296]
## Description

Implement `emit_order_created` function in the `EventEmitter` library.

File: `src/event/event_emitter.cairo`.

Function signature:
```rust
    fn emit_order_created(key: felt252, order: Order);
```

---

Implement `emit_order_executed` function in the `EventEmitter` library.

File: `src/event/event_emitter.cairo`.

Function signature:
```rust
    fn emit_order_executed(
        key: felt252,
        secondary_order_type: SecondaryOrderType
    );
```

---

Implement `emit_order_updated` function in the `EventEmitter` library.

File: `src/event/event_emitter.cairo`.

Function signature:
```rust
    fn emit_order_updated(
        key: felt252,
        size_delta_usd: u128,
        acceptable_price: u128
        trigger_price: u128,
        min_output_amount: u128
    );
```

---

Implement `emit_order_size_delta_auto_updated` function in the `EventEmitter` library.

File: `src/event/event_emitter.cairo`.

Function signature:
```rust
    fn emit_order_size_delta_auto_updated(
        key: felt252,
        size_delta_usd: u128,
        next_size_delta_usd: u128
    );
```

---

Implement `emit_order_collateral_delta_amount_auto_updated` function in the `EventEmitter` library.

File: `src/event/event_emitter.cairo`.

Function signature:
```rust
    fn emit_order_collateral_delta_amount_auto_updated(
        key: felt252,
        collateral_delta_amount: u128,
        next_collateral_delta_amount: u128
    );
```

---

Implement `emit_order_cancelled` function in the `EventEmitter` library.

File: `src/event/event_emitter.cairo`.

Function signature:
```rust
    fn emit_order_cancelled(
        key: felt252,
        reason: felt252,
        reason_bytes: Array<felt252>
    );
```

---

Implement `emit_order_frozen` function in the `EventEmitter` library.

File: `src/event/event_emitter.cairo`.

Function signature:
```rust
    fn emit_order_frozen(
        key: felt252,
        reason: felt252,
        reason_bytes: Array<felt252>
    );
```

## Acceptance criteria

- Function is implemented and well commented.
- Associated unit tests (nominal and failure) are implemented and passing.

## Resources
- [emitOrderCreated function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/order/OrderEventUtils.sol#L21)
- [emitOrderExecuted function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/order/OrderEventUtils.sol#L67)
- [emitOrderUpdated function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/order/OrderEventUtils.sol#L87)
- [emitOrderSizeDeltaAutoUpdated function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/order/OrderEventUtils.sol#L113)
- [emitOrderCollateralDeltaAmountAutoUpdated function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/order/OrderEventUtils.sol#L135)
- [emitOrderCancelled function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/order/OrderEventUtils.sol#L157)
- [emitOrderFrozen function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/order/OrderEventUtils.sol#L181)

**Comment by ermvrs** [comment]
Do we gonna implement it like at https://github.com/keep-starknet-strange/satoru/pull/293

I mean these methods to call event_emitter to emit new event on each function. If so I can get this one.

**Comment by sparqet** [comment]
> Do we gonna implement it like at #293
> 
> I mean these methods to call event_emitter to emit new event on each function. If so I can get this one.

yes we have to do it the same way as #293 👍

Assigned ! 🚀
