### ISSUE TITLE
Feat: Implement the functions in the `WithdrawalHandler` contract.

### ISSUE THREAD

**Issue by sparqet** [keep-starknet-strange/satoru#309]
## Description

Implement the `create_withdrawal` function in the `WithdrawalHandler` contract.

File: `src/exchange/withdrawal_handler.cairo`.

Function signature:
```rust
    /// Creates a withdrawal in the withdrawal store.
    /// # Arguments
    /// * `account` - The withdrawaling account.
    /// * `params` - The parameters used to create the withdrawal.
    /// # Returns
    /// The key of where the withdrawal is stored.
    fn create_withdrawal(
        ref self: TContractState, account: ContractAddress, params: CreateWithdrawalParams
    ) -> felt252;
```

---

Implement the `cancel_withdrawal` function in the `WithdrawalHandler` contract.

File: `src/exchange/withdrawal_handler.cairo`.

Function signature:
```rust
    /// Cancels a withdrawal.
    /// # Arguments
    /// * `key` - The key of the withdrawal to cancel.
    fn cancel_withdrawal(ref self: TContractState, key: felt252);
```

---

Implement the `execute_withdrawal` function in the `WithdrawalHandler` contract.

File: `src/exchange/withdrawal_handler.cairo`.

Function signature:
```rust
    /// Executes a withdrawal.
    /// # Arguments
    /// * `key` - The key of the withdrawal to execute.
    /// * `oracle_params` - The oracle params to set prices before execution.
    fn execute_withdrawal(ref self: TContractState, key: felt252, oracle_params: SetPricesParams);
```

---

Implement the `simulate_execute_withdrawal` function in the `WithdrawalHandler` contract.

File: `src/exchange/withdrawal_handler.cairo`.

Function signature:
```rust
    /// Simulates execution of a withdrawal to check for any error.
    /// # Arguments
    /// * `key` - The key of the withdrawal to execute.
    /// * `oracle_params` - The oracle params to set prices before simulation.
    fn simulate_execute_withdrawal(
        ref self: TContractState, key: felt252, params: SimulatePricesParams
    );
```

---

Implement the `execute_withdrawal_keeper` function in the `WithdrawalHandler` contract.

File: `src/exchange/withdrawal_handler.cairo`.

Function signature:
```rust
    /// Executes a withdrawal with keeper.
    /// # Arguments
    /// * `key` - The key of the withdrawal to execute.
    /// * `oracle_params` - The oracle params to set prices before execution.
    /// * `keeper` - The keeper executing the withdrawal.
    fn execute_withdrawal_keeper(
        ref self: TContractState,
        key: felt252,
        oracle_params: SetPricesParams,
        keeper: ContractAddress
    );
```

---

Implement the internal`handle_withdrawal_error` function in the `WithdrawalHandler` contract.

File: `src/exchange/withdrawal_handler.cairo`.

Function signature:
```rust
    /// Handles error from withdrawal.
    /// # Arguments
    /// * `key` - The key of the withdrawal to handle error for.
    /// * `starting_gas` - The starting gas of the transaction.
    /// * `reason_bytes` - The reason of the error.
    fn handle_withdrawal_error(
        ref self: ContractState, key: felt252, starting_gas: u128, reason_bytes: Array<felt252>); 
```

## Acceptance criteria

- Function is implemented and well commented.
- Associated unit tests (nominal and failure) are implemented and passing.

## Resources

- [createWithdrawal function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/exchange/WithdrawalHandler.sol#L48)
- [cancelWithdrawal function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/exchange/WithdrawalHandler.sol#L65)
- [executeWithdrawal function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/exchange/WithdrawalHandler.sol#L94)
- [simulateExecuteWithdrawal function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/exchange/WithdrawalHandler.sol#L123)
- [_executeWithdrawal function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/exchange/WithdrawalHandler.sol#L146)
- [_handleWithdrawalError function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/exchange/WithdrawalHandler.sol#L180)

**Comment by ermvrs** [comment]
I can take that one aswell. As I know we need to wait to merge the last one. :))

**Comment by sparqet** [comment]
You got it ! Assigned

**Comment by sparqet** [comment]
following issue required for this issue:
- #267 
- #248 
- #245 
- #295 
- #297 
- oracle.cairo

following functions required but not in any issue :
- [createWithdrawal function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/exchange/WithdrawalHandler.sol#L48)
- [cancelWithdrawal function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/exchange/WithdrawalHandler.sol#L65)
- [executeWithdrawal function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/exchange/WithdrawalHandler.sol#L94)
- [simulateExecuteWithdrawal function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/exchange/WithdrawalHandler.sol#L123)
- [_executeWithdrawal function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/exchange/WithdrawalHandler.sol#L146)
- [_handleWithdrawalError function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/exchange/WithdrawalHandler.sol#L180)
