### ISSUE TITLE
Test: add tests for `PositionEvents` functions of the `EventEmitter` contract.

### ISSUE THREAD

**Issue by sparqet** [keep-starknet-strange/satoru#318]
## Description

Add tests using [spy_events](https://foundry-rs.github.io/starknet-foundry/appendix/cheatcodes/spy_events.html) of Starknet Foundry.

Functions to test : 

- [emit_position_increase](https://github.com/keep-starknet-strange/satoru/blob/993cbc7ad6f39a9d6c68d5a60a179a042d70b1b5/src/event/event_emitter.cairo#L154)
- [emit_position_decrease](https://github.com/keep-starknet-strange/satoru/blob/993cbc7ad6f39a9d6c68d5a60a179a042d70b1b5/src/event/event_emitter.cairo#L158)
- [emit_insolvent_close_info](https://github.com/keep-starknet-strange/satoru/blob/993cbc7ad6f39a9d6c68d5a60a179a042d70b1b5/src/event/event_emitter.cairo#L172)
- [emit_insufficient_funding_fee_payment](https://github.com/keep-starknet-strange/satoru/blob/993cbc7ad6f39a9d6c68d5a60a179a042d70b1b5/src/event/event_emitter.cairo#L181)
- [emit_position_fees_collected](https://github.com/keep-starknet-strange/satoru/blob/993cbc7ad6f39a9d6c68d5a60a179a042d70b1b5/src/event/event_emitter.cairo#L192)
- [emit_position_fees_info](https://github.com/keep-starknet-strange/satoru/blob/993cbc7ad6f39a9d6c68d5a60a179a042d70b1b5/src/event/event_emitter.cairo#L205)

**Comment by 0xTitan** [comment]
Can i continue with this one ?

**Comment by sparqet** [comment]
of course ! Assigned !
