### ISSUE TITLE
Test: add tests for `ReferralEvents` functions of the `EventEmitter` contract.

### ISSUE THREAD

**Issue by sparqet** [keep-starknet-strange/satoru#319]
## Description

Add tests using [spy_events](https://foundry-rs.github.io/starknet-foundry/appendix/cheatcodes/spy_events.html) of Starknet Foundry.

Functions to test : 

- [emit_affiliate_reward_updated](https://github.com/keep-starknet-strange/satoru/blob/993cbc7ad6f39a9d6c68d5a60a179a042d70b1b5/src/event/event_emitter.cairo#L259)
- [emit_affiliate_reward_claimed](https://github.com/keep-starknet-strange/satoru/blob/993cbc7ad6f39a9d6c68d5a60a179a042d70b1b5/src/event/event_emitter.cairo#L270)

**Comment by FabienCoutant** [comment]
Hello, can I take this one please :)

**Comment by sparqet** [comment]
Hello ! yes of course, assigned !
