### ISSUE TITLE
Feat: Implement the functions in the `Oracle` contract.

### ISSUE THREAD

**Issue by Sk8erboi84** [keep-starknet-strange/satoru#320]
## Description

Implement the `set_prices` function in the `Oracle` contract.

File: `src/oracle/oracle.cairo`.

Function signature:
```rust
    /// The signed prices represent the price of one unit of the token using a value
    /// with 30 decimals of precision.
    ///
    /// # Arguments
    /// * `data_store` - The data store.
    /// * `event_emitter` - The event emitter.
    /// * `params` - The set price params.
    fn set_prices(
        ref self: TContractState,
        data_store: IDataStoreSafeDispatcher,
        event_emitter: IEventEmitterDispatcher,
        params: SetPricesParams,
    );
```
---
Implement the `set_primary_price` function in the `Oracle` contract.

File: `src/oracle/oracle.cairo`.

Function signature:
```rust
    /// Set the primary price
    /// # Arguments
    /// * `token` - The token to set the price for.
    /// * `price` - The price value to set to.
    fn set_primary_price(ref self: TContractState, token: ContractAddress, price: Price);
```
---
Implement the `clear_all_prices` function in the `Oracle` contract.

File: `src/oracle/oracle.cairo`.

Function signature:
```rust
    /// Clear all prices
    fn clear_all_prices(ref self: TContractState);
```
---
Implement the `get_tokens_with_prices_count` function in the `Oracle` contract.

File: `src/oracle/oracle.cairo`.

Function signature:
```rust
    /// Get the length of tokens_with_prices
    /// # Returns
    /// The length of tokens_with_prices
    fn get_tokens_with_prices_count(self: @TContractState) -> u128;
```
---
Implement the `get_tokens_with_prices` function in the `Oracle` contract.

File: `src/oracle/oracle.cairo`.

Function signature:
```rust
    /// Get the tokens_with_prices from start to end.
    /// # Arguments
    /// * `start` - The start index, the value for this index will be included.
    /// * `end` -  The end index, the value for this index will be excluded.
    /// # Returns
    /// The tokens of tokens_with_prices for the specified indexes.
    fn get_tokens_with_prices(
        self: @TContractState, start: u128, end: u128
    ) -> Array<ContractAddress>;
```
---
Implement the `get_primary_price` function in the `Oracle` contract.

File: `src/oracle/oracle.cairo`.

Function signature:
```rust
    /// Get the primary price of a token.
    /// # Arguments
    /// * `token` - The token to get the price for.
    /// # Returns
    /// The primary price of a token.
    fn get_primary_price(self: @TContractState, token: ContractAddress) -> Price;
```
---
Implement the `get_stable_price` function in the `Oracle` contract.

File: `src/oracle/oracle.cairo`.

Function signature:
```rust
    /// Get the stable price of a token.
    /// # Arguments
    /// * `token` - The token to get the price for.
    /// # Returns
    /// The stable price of a token.
    fn get_stable_price(self: @TContractState, token: ContractAddress) -> u128;
```
---
Implement the `get_price_feed_multiplier` function in the `Oracle` contract.

File: `src/oracle/oracle.cairo`.

Function signature:
```rust
    /// # Arguments
    /// * `data_store` - The data store dispatcher.
    /// * `token` - The token to get the price for.
    /// # Returns
    /// The price feed multiplier.
    fn get_price_feed_multiplier(
        self: @TContractState, data_store: IDataStoreSafeDispatcher, token: ContractAddress,
    ) -> u128;
```
---
Implement the `validate_prices` function in the `Oracle` contract.

File: `src/oracle/oracle.cairo`.

Function signature:
```rust
    /// Validate prices in `params` for oracles.
    /// # Arguments
    /// * `data_store` - The `DataStore` contract dispatcher.
    /// * `params` - The parameters used to set prices in oracle.
    fn validate_prices(
        self: @TContractState, data_store: IDataStoreSafeDispatcher, params: SetPricesParams,
    ) -> Array<ValidatedPrice>;
```

## Acceptance criteria

- Function is implemented and well commented.
- Associated unit tests (nominal and failure) are implemented and passing.

## Resources

- [setPrices function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/oracle/Oracle.sol#L199)
- [setPrimaryPrice function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/oracle/Oracle.sol#L224)
- [clearAllPrices function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/oracle/Oracle.sol#L229)
- [getTokensWithPricesCount function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/oracle/Oracle.sol#L239)
- [getTokensWithPrices function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/oracle/Oracle.sol#L247)
- [getPrimaryPrice function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/oracle/Oracle.sol#L254)
- [getStablePrice function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/oracle/Oracle.sol#L269)
- [getPriceFeedMultiplier function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/oracle/Oracle.sol#L285)
- [validatePrices function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/oracle/Oracle.sol#L295)

**Comment by ametel01** [comment]
happy to take this

**Comment by sparqet** [comment]
yes please ! assigned
