### ISSUE TITLE
Test: add tests for `OrderEvents` functions of the `EventEmitter` contract.

### ISSUE THREAD

**Issue by sparqet** [keep-starknet-strange/satoru#321]
## Description

Add tests using [spy_events](https://foundry-rs.github.io/starknet-foundry/appendix/cheatcodes/spy_events.html) of Starknet Foundry.

Functions to test : 

- [emit_order_created](https://github.com/keep-starknet-strange/satoru/blob/993cbc7ad6f39a9d6c68d5a60a179a042d70b1b5/src/event/event_emitter.cairo#L218)
- [emit_order_executed](https://github.com/keep-starknet-strange/satoru/blob/993cbc7ad6f39a9d6c68d5a60a179a042d70b1b5/src/event/event_emitter.cairo#L221)
- [emit_order_updated](https://github.com/keep-starknet-strange/satoru/blob/993cbc7ad6f39a9d6c68d5a60a179a042d70b1b5/src/event/event_emitter.cairo#L226)
- [emit_order_size_delta_auto_updated](https://github.com/keep-starknet-strange/satoru/blob/993cbc7ad6f39a9d6c68d5a60a179a042d70b1b5/src/event/event_emitter.cairo#L236)
- [emit_order_collateral_delta_amount_auto_updated](https://github.com/keep-starknet-strange/satoru/blob/993cbc7ad6f39a9d6c68d5a60a179a042d70b1b5/src/event/event_emitter.cairo#L241)
- [emit_order_cancelled](https://github.com/keep-starknet-strange/satoru/blob/993cbc7ad6f39a9d6c68d5a60a179a042d70b1b5/src/event/event_emitter.cairo#L249)
- [emit_order_frozen](https://github.com/keep-starknet-strange/satoru/blob/993cbc7ad6f39a9d6c68d5a60a179a042d70b1b5/src/event/event_emitter.cairo#L254)

**Comment by FabienCoutant** [comment]
Can I continue with this one please? :)

**Comment by Sk8erboi84** [comment]
Sure! Assigned ! 🔥
