### ISSUE TITLE
Test: add tests for `WithdrawalEvents` functions of the `EventEmitter` contract.

### ISSUE THREAD

**Issue by sparqet** [keep-starknet-strange/satoru#323]
## Description

Add tests using [spy_events](https://foundry-rs.github.io/starknet-foundry/appendix/cheatcodes/spy_events.html) of Starknet Foundry.

Functions to test : 

- [emit_withdrawal_created](https://github.com/keep-starknet-strange/satoru/blob/993cbc7ad6f39a9d6c68d5a60a179a042d70b1b5/src/event/event_emitter.cairo#L142)
- [emit_withdrawal_executed](https://github.com/keep-starknet-strange/satoru/blob/993cbc7ad6f39a9d6c68d5a60a179a042d70b1b5/src/event/event_emitter.cairo#L145)
- [emit_withdrawal_cancelled](https://github.com/keep-starknet-strange/satoru/blob/993cbc7ad6f39a9d6c68d5a60a179a042d70b1b5/src/event/event_emitter.cairo#L148)

**Comment by FabienCoutant** [comment]
Can I take it ? :)

**Comment by Sk8erboi84** [comment]
Yes!! Assigned 🔥
