### ISSUE TITLE
Feat: Implement the functions in the `base_order_utils` library.

### ISSUE THREAD

**Issue by Sk8erboi84** [keep-starknet-strange/satoru#327]
## Description

Implement the `is_market_order` function in the `base_order_utils` library.

File: `src/order/base_order_utils.cairo`.

Function signature:
```rust
/// Check if an order_type is a market order.
/// # Arguments
/// * `order_type` - The order type.
/// # Return
/// Return whether an order_type is a market order
fn is_market_order(order_type: OrderType) -> bool;
```
---
Implement the `is_limit_order` function in the `base_order_utils` library.

File: `src/order/base_order_utils.cairo`.

Function signature:
```rust
/// Check if an orderType is a limit order.
/// # Arguments
/// * `order_type` - The order type.
/// # Return
/// Return whether an order_type is a limit order
fn is_limit_order(order_type: OrderType) -> bool;
```
---

Implement the `is_swap_order` function in the `base_order_utils` library.

File: `src/order/base_order_utils.cairo`.

Function signature:
```rust
/// Check if an orderType is a swap order.
/// # Arguments
/// * `order_type` - The order type.
/// # Return
/// Return whether an order_type is a swap order
fn is_swap_order(order_type: OrderType) -> bool;
```
---
Implement the `is_position_order` function in the `base_order_utils` library.

File: `src/order/base_order_utils.cairo`.

Function signature:
```rust
/// Check if an orderType is a position order.
/// # Arguments
/// * `order_type` - The order type.
/// # Return
/// Return whether an order_type is a position order
fn is_position_order(order_type: OrderType) -> bool;
```
---
Implement the `is_increase_order` function in the `base_order_utils` library.

File: `src/order/base_order_utils.cairo`.

Function signature:
```rust
/// Check if an orderType is an increase order.
/// # Arguments
/// * `order_type` - The order type.
/// # Return
/// Return whether an order_type is an increase order
fn is_increase_order(order_type: OrderType) -> bool;
```
---
Implement the `is_decrease_order` function in the `base_order_utils` library.

File: `src/order/base_order_utils.cairo`.

Function signature:
```rust
/// Check if an orderType is a decrease order.
/// # Arguments
/// * `order_type` - The order type.
/// # Return
/// Return whether an order_type is a decrease order
fn is_decrease_order(order_type: OrderType) -> bool;
```
---
Implement the `is_liquidation_order` function in the `base_order_utils` library.

File: `src/order/base_order_utils.cairo`.

Function signature:
```rust
/// Check if an orderType is a liquidation order.
/// # Arguments
/// * `order_type` - The order type.
/// # Return
/// Return whether an order_type is a liquidation order
fn is_liquidation_order(order_type: OrderType) -> bool;
```
---
Implement the `validate_order_trigger_price` function in the `base_order_utils` library.

File: `src/order/base_order_utils.cairo`.

Function signature:
```rust
fn validate_order_trigger_price(
    oracle: IOracleSafeDispatcher,
    index_token: ContractAddress,
    order_type: OrderType,
    trigger_price: u128,
    is_long: bool
);
```
---
Implement the `get_execution_price_for_increase` function in the `base_order_utils` library.

File: `src/order/base_order_utils.cairo`.

Function signature:
```rust
fn get_execution_price_for_increase(
    size_delta_usd: u128, size_delta_in_tokens: u128, acceptable_price: u128, is_long: bool
) -> u128;
```
---
Implement the `get_execution_price_for_decrease` function in the `base_order_utils` library.

File: `src/order/base_order_utils.cairo`.

Function signature:
```rust
fn get_execution_price_for_decrease(
    index_token_price: Price,
    position_size_in_usd: u128,
    position_size_in_tokens: u128,
    size_delta_usd: u128,
    price_impact_usd: i128,
    acceptable_price: u128,
    is_long: bool
) -> u128;
```
---
Implement the `validate_non_empty_order` function in the `base_order_utils` library.

File: `src/order/base_order_utils.cairo`.

Function signature:
```rust
fn validate_non_empty_order(order: Order);
```

## Acceptance criteria

- Function is implemented and well commented.
- Associated unit tests (nominal and failure) are implemented and passing.

## Resources
- [isMarketOrder function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/order/BaseOrderUtils.sol#L126)
- [isLimitOrder function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/order/BaseOrderUtils.sol#L136)
- [isSwapOrder function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/order/BaseOrderUtils.sol#L145)
- [isPositionOrderfunction in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/order/BaseOrderUtils.sol#L153)
- [isIncreaseOrder function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/order/BaseOrderUtils.sol#L160)
- [isDecreaseOrderfunction in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/order/BaseOrderUtils.sol#L168)
- [isLiquidationOrder function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/order/BaseOrderUtils.sol#L178)
- [validateOrderTriggerPrice function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/order/BaseOrderUtils.sol#L213)
- [getExecutionPriceForIncrease function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/order/BaseOrderUtils.sol#L281)
- [getExecutionPriceForDecrease function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/order/BaseOrderUtils.sol#L325)
- [validateNonEmptyOrder function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/order/BaseOrderUtils.sol#L444)

**Comment by delaaxe** [comment]
I can go on with this bad boy

**Comment by Sk8erboi84** [comment]
Sure I can assign it to you, but some of the imports haven't implemented yet.

**Comment by sparqet** [comment]
following issue required for this issue:
- #320 
- SwapHandler

following functions required but not in any issue :
- [claimFees function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/fee/FeeHandler.sol#L28)
