### ISSUE TITLE
Feat: Implement the functions in the `decrease_position_collateral_utils` library.

### ISSUE THREAD

**Issue by sparqet** [keep-starknet-strange/satoru#328]
## Description

Implement the `process_collateral` function in the `decrease_position_collateral_utils` library.

File: `src/position/decrease_position_collateral_utils.cairo`.

Function signature:
```rust
/// Handle the collateral changes of the position.
/// # Returns
/// (DecreasePositionCollateralValues, PositionFees)
#[inline(always)]
fn process_collateral(
    params: UpdatePositionParams, cache: DecreasePositionCache
) -> (DecreasePositionCollateralValues, PositionFees)
```

---

Implement the `get_execution_price` function in the `decrease_position_collateral_utils` library.

File: `src/position/decrease_position_collateral_utils.cairo`.

Function signature:
```rust
/// Compute execution price of the position update.
/// # Arguments
/// * `params` - The parameters of the position update.
/// * `index_token_price` - The price of the index token.
/// (price_impact_usd, price_impact_diff_usd, execution_price)
fn get_execution_price(
    params: UpdatePositionParams, index_token_price: Price
) -> (i128, u128, u128)
```

---

Implement the `pay_for_cost` function in the `decrease_position_collateral_utils` library.

File: `src/position/decrease_position_collateral_utils.cairo`.

Function signature:
```rust
/// Pay costs of the position update.
/// # Arguments
/// * `params` - The parameters of the position update.
/// * `values` - The struct filled with values computed in process_collateral.
/// * `prices` - The prices of tokens in the market.
/// * `collateral_token_price` - The prices of the collateral token.
/// * `cost_usd` - The total cost in usd.
/// # Returns
/// Updated DecreasePositionCollateralValues and output of pay for cost.
fn pay_for_cost(
    params: UpdatePositionParams,
    values: DecreasePositionCollateralValues,
    prices: MarketPrices,
    collateral_token_price: Price,
    cost_usd: u128,
) -> (DecreasePositionCollateralValues, PayForCostResult)
```

---

Implement the `handle_early_return` function in the `decrease_position_collateral_utils` library.

File: `src/position/decrease_position_collateral_utils.cairo`.

Function signature:
```rust
/// Handle early return case where there is still remaining costs.
/// # Arguments
/// * `params` - The parameters of the position update.
/// * `values` - The struct filled with values computed in process_collateral.
/// * `fees` - The position fees.
/// * `collateral_cache` - The struct used as cache in process_collateral.
/// # Returns
/// Updated DecreasePositionCollateralValues and position fees.
fn handle_early_return(
    params: UpdatePositionParams,
    values: DecreasePositionCollateralValues,
    fees: PositionFees,
    collateral_cache: ProcessCollateralCache,
) -> (DecreasePositionCollateralValues, PositionFees)
```

---

Implement the `get_empty_fees` function in the `decrease_position_collateral_utils` library.

File: `src/position/decrease_position_collateral_utils.cairo`.

Function signature:
```rust
/// Return empty fees struct using fees struct given in parameter.
/// Keep useful values such as accumulated funding fees.
/// # Arguments
/// * `fees` - The PositionFees struct used to get the new empty struct.
/// # Returns
/// An empty PositionFees struct.
fn get_empty_fees(fees: PositionFees) -> PositionFees
```

## Acceptance criteria

- Function is implemented and well commented.
- Associated unit tests (nominal and failure) are implemented and passing.

## Resources
- [processCollateral function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/position/DecreasePositionCollateralUtils.sol#L65)
- [getExecutionPrice function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/position/DecreasePositionCollateralUtils.sol#L532)
- [payForCost function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/position/DecreasePositionCollateralUtils.sol#L607)
- [handleEarlyReturn function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/position/DecreasePositionCollateralUtils.sol#L669)
- [getEmptyFees function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/position/DecreasePositionCollateralUtils.sol#L702)

**Comment by zarboq** [comment]
I'm doing this one :rocket:
