### ISSUE TITLE
Feat: Implement the functions in the `decrease_position_swap_utils` library.

### ISSUE THREAD

**Issue by sparqet** [keep-starknet-strange/satoru#329]
## Description

Implement the `swap_withdrawn_collateral_to_pnl_token` function in the `decrease_position_swap_utils ` library.

File: `src/position/decrease_position_swap_utils.cairo`.

Function signature:
```rust
/// Swap the withdrawn collateral from collateral_token to pnl_token if needed.
#[inline(always)]
fn swap_withdrawn_collateral_to_pnl_token(
    params: UpdatePositionParams, values: DecreasePositionCollateralValues
) -> DecreasePositionCollateralValues
```

---

Implement the `swap_profit_to_collateral_token` function in the `decrease_position_swap_utils` library.

File: `src/position/decrease_position_swap_utils.cairo`.

Function signature:
```rust
/// Swap the realized profit from the pnlToken to the collateralToken if needed.
/// # Arguments
/// * `pnl_token` - The profit token.
/// * `pnl_amount` - The amount of profit in usd.
/// # Returns
/// DecreasePositionCollateralValues
#[inline(always)]
fn swap_profit_to_collateral_token(
    params: UpdatePositionParams, pnl_token: ContractAddress, profit_amount: u128
) -> (bool, u128)
```

## Acceptance criteria

- Function is implemented and well commented.
- Associated unit tests (nominal and failure) are implemented and passing.

## Resources
- [swapWithdrawnCollateralToPnlToken function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/position/DecreasePositionSwapUtils.sol#L12)
- [swapProfitToCollateralToken function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/position/DecreasePositionSwapUtils.sol#L55)

**Comment by ermvrs** [comment]
Are there any blocking issues for this? Also we cant handle try-catch so if possible to implement this one. As I see its blocking other issues , I can take this one if nothing blocking this right now?
