### ISSUE TITLE
Feat: Implement `decrease_position` in the `decrease_position_utils` library.

### ISSUE THREAD

**Issue by sparqet** [keep-starknet-strange/satoru#330]
## Description

Implement the `decrease_position` function in the `decrease_position_utils` library.

File: `src/position/decrease_position_utils.cairo`.

Function signature:
```rust
/// The decrease_position function decreases the size of an existing position
/// in a market. It takes a UpdatePositionParams object as an input, which
/// includes information about the position to be decreased, the market in
/// which the position exists, and the order that is being used to decrease the position.
///
/// The function first calculates the prices of the tokens in the market, and then
/// checks whether the position is liquidatable based on the current market prices.
/// If the order is a liquidation order and the position is not liquidatable, the function reverts.
///
/// If there is not enough collateral in the position to complete the decrease,
/// the function reverts. Otherwise, the function updates the position's size and
/// collateral amount, and increments the claimable funding amount for
/// the market if necessary.
///
/// Finally, the function returns a DecreasePositionResult object containing
/// information about the outcome of the decrease operation, including the amount
/// of collateral removed from the position and any fees that were paid.
fn decrease_position(params: UpdatePositionParams) -> DecreasePositionResult
```

## Acceptance criteria

- Function is implemented and well commented.
- Associated unit tests (nominal and failure) are implemented and passing.

## Resources
- [decreasePosition function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/position/DecreasePositionUtils.sol#L63)

**Comment by FabienCoutant** [comment]
May I have this one ? :)

**Comment by sparqet** [comment]
Assigned !

**Comment by FabienCoutant** [comment]
following issue as required to be done:
- #250
- #243
- #327
- #328
- #329 

following functions missing :
- [getMarketPrices function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/market/MarketUtils.sol#L194)
- [getCachedTokenPrice function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/market/MarketUtils.sol#L177)
- [setSizeDeltaUsd function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/order/Order.sol#L256)
- [getPositionPnlUsd function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/position/PositionUtils.sol#L169) 
- [collateralAmount function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/position/PositionUtils.sol#L169) 
- [updateFundingAndBorrowingState function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/position/PositionUtils.sol#L493)
- [isPositionLiquidatable function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/position/PositionUtils.sol#L307)
- [getCumulativeBorrowingFactor function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/market/MarketUtils.sol#L2033)
- [updateTotalBorrowing function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/position/PositionUtils.sol#L524)
- [incrementClaimableFundingAmount function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/position/PositionUtils.sol#L545)
- [updateOpenInterest function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/position/PositionUtils.sol#L573)
- [handleReferral function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/position/PositionUtils.sol#L599)
- [validatePosition function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/position/PositionUtils.sol#L264)
