### ISSUE TITLE
Feat: Implement the functions in the `increase_position_utils` library.

### ISSUE THREAD

**Issue by sparqet** [keep-starknet-strange/satoru#331]
## Description

Implement the `increase_position` function in the `increase_position_utils` library.

File: `src/position/increase_position_utils.cairo`.

Function signature:
```rust
/// The increasePosition function is used to increase the size of a position
/// in a market. This involves updating the position's collateral amount,
/// calculating the price impact of the size increase, and updating the position's
/// size and borrowing factor. This function also applies fees to the position
/// and updates the market's liquidity pool based on the new position size.
fn increase_position(params: UpdatePositionParams, collateral_increment_amount: u128)
```

---

Implement the `process_collateral` function in the `increase_position_utils` library.

File: `src/position/increase_position_utils.cairo`.

Function signature:
```rust
/// Handle the collateral changes of the position.
/// # Arguments
/// * `collateral_delta_amount` - The change in the position's collateral.
fn process_collateral(
    params: UpdatePositionParams,
    collateral_token_price: Price,
    collateral_delta_amount: i128,
    price_impact_usd: i128,
) -> (i128, PositionFees)
```

---

Implement the `get_execution_price` function in the `increase_position_utils` library.

File: `src/position/increase_position_utils.cairo`.

Function signature:
```rust
/// # Returns
/// price_impact_usd, price_impact_amount, size_delta_in_tokens, execution_price
fn get_execution_price(
    params: UpdatePositionParams, index_token_price: Price
) -> (i128, i128, u128, u128)
```

## Acceptance criteria

- Function is implemented and well commented.
- Associated unit tests (nominal and failure) are implemented and passing.

## Resources
- [increasePosition function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/position/IncreasePositionUtils.sol#L57)
- [processCollateral function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/position/IncreasePositionUtils.sol#L256)
- [getExecutionPrice function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/position/IncreasePositionUtils.sol#L318)

**Comment by h3lio5** [comment]
Can I take this ser?

**Comment by sparqet** [comment]
sure !

**Comment by sparqet** [comment]
following issue required for this issue:
- #250
- #243
- #327
- #328
- #329 

following functions that require to finish other issues  :
- [increasePosition function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/position/IncreasePositionUtils.sol#L57)
- [processCollateral function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/position/IncreasePositionUtils.sol#L256)
- [getExecutionPrice function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/position/IncreasePositionUtils.sol#L318)

**Comment by h3lio5** [comment]
Those issues are blocking my issue? 🫠

**Comment by sparqet** [comment]
Yes, you can check maybe there's some functions you can do

**Comment by sparqet** [comment]
Hi @h3lio5 ! Do yoy have any news on your issue ?

**Comment by h3lio5** [comment]
apologise for the delay! I was waiting for the blocking issues to finish and hadn’t checked on them. I will get back to it again.

**Comment by sparqet** [comment]
If there is blocking issues, you just need to write the skeleton of the tests and push a PR

**Comment by sparqet** [comment]
@h3lio5 any news ?
