### ISSUE TITLE
Feat: Implement the functions in the `decrease_order_utils` library.

### ISSUE THREAD

**Issue by Sk8erboi84** [keep-starknet-strange/satoru#334]
## Description

Implement the `process_order` function in the `decrease_order_utils` library.

File: `src/order/decrease_order_utils.cairo`.

Function signature:
```rust
fn process_order(params: ExecuteOrderParams);
```
---
Implement the `validate_oracle_block_numbers` function in the `decrease_order_utils` library.

File: `src/order/decrease_order_utils.cairo`.

Function signature:
```rust
fn validate_oracle_block_numbers(
    min_oracle_block_numbers: Array<u128>,
    max_oracle_block_numbers: Array<u128>,
    order_type: Order,
    order_updated_at_block: u128,
    position_increased_at_block: u128,
    position_decrease_at_block: u128
);
```
---
Implement the `validate_output_amount` function in the `decrease_order_utils` library.

File: `src/order/decrease_order_utils.cairo`.

Function signature:
```rust
fn validate_output_amount(
    oracle: IOracleSafeDispatcher,
    output_token: ContractAddress,
    output_amount: u128,
    min_output_amount: u128,
    max_output_amount: u128
);
```
---
Implement the `validate_output_amount_secondary` function in the `decrease_order_utils` library.

File: `src/order/decrease_order_utils.cairo`.

Function signature:
```rust
fn validate_output_amount_secondary(
    oracle: IOracleSafeDispatcher,
    output_token: ContractAddress,
    output_amount: u128,
    min_output_amount: u128,
    secondary_output_token: u128,
    secondary_output_amount: u128,
    max_output_amount: u128
);
```
---
Implement the `handle_swap_error` function in the `decrease_order_utils` library.

File: `src/order/decrease_order_utils.cairo`.

Function signature:
```rust
fn handle_swap_error(
    oracle: IOracleSafeDispatcher,
    order: Order,
    result: DecreasePositionResult,
    reason: felt252,
    reason_bytes: Array<felt252>
);
```
---
Implement the `get_output_event_data` function in the `decrease_order_utils` library.

File: `src/order/decrease_order_utils.cairo`.

Function signature:
```rust
fn get_output_event_data(
    output_token: ContractAddress,
    output_amount: u128,
    secondary_output_token: ContractAddress,
    secondary_output_amount: u128
);
```
---

## Acceptance criteria

- Function is implemented and well commented.
- Associated unit tests (nominal and failure) are implemented and passing.

## Resources
- [processOrder function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/order/DecreaseOrderUtils.sol#L29)
- [validateOracleBlockNumbers function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/order/DecreaseOrderUtils.sol#L151)
- [_validateOutputAmount function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/order/DecreaseOrderUtils.sol#L192)
- [_validateOutputAmount function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/order/DecreaseOrderUtils.sol#L207)
- [_handleSwapError function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/order/DecreaseOrderUtils.sol#L228)
- [getOutputEventData function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/order/DecreaseOrderUtils.sol#L252)

**Comment by Xavek** [comment]
would like to implement it.

**Comment by Sk8erboi84** [comment]
Sure, assigned 🔥

**Comment by sparqet** [comment]
Hi @Xavek ! Do you have any news on your issue ?

**Comment by Xavek** [comment]
Yeah. Sorry, couldn't finish due to time constrain, yet to do the testing actually. If others are hungry for issues then unassign me and take away. Once again sorry I absolutely forgot that I was assigned. I would try others whenever I free down the line. Thank you for remainder @sparqet

**Comment by ametel01** [comment]
i can take this if it's unassigned

**Comment by Sk8erboi84** [comment]
> @sparqet i can take this if it's unassigned

I assigned you this issue : https://github.com/keep-starknet-strange/satoru/issues/427
