### ISSUE TITLE
Feat: Implement the functions in the `increase_order_utils` library.

### ISSUE THREAD

**Issue by Sk8erboi84** [keep-starknet-strange/satoru#337]
## Description

Implement the `process_order` function in the `increase_order_utils` library.

File: `src/order/increase_order_utils.cairo`.

Function signature:
```rust
fn process_order(params: ExecuteOrderParams);
```
---
Implement the `validate_oracle_block_numbers` function in the `increase_order_utils` library.

File: `src/order/increase_order_utils.cairo`.

Function signature:
```rust
fn validate_oracle_block_numbers(
    min_oracle_block_numbers: Array<u128>,
    max_oracle_block_numbers: Array<u128>,
    order_type: Order,
    order_updated_at_block: u128);
```

## Acceptance criteria

- Function is implemented and well commented.
- Associated unit tests (nominal and failure) are implemented and passing.

## Resources
- [processOrder function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/order/IncreaseOrderUtils.sol#L20)
- [validateOracleBlockNumbers function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/order/IncreaseOrderUtils.sol#L84)

**Comment by ftupas** [comment]
Hello, may I take this?

**Comment by sparqet** [comment]
Sure ! Assigned

**Comment by sparqet** [comment]
following issue required for this issue:
- #269 
- #331
- #296
- SwapUtils

following functions that require to finish other issues  :
- [processOrder function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/order/IncreaseOrderUtils.sol#L20)
- [validateOracleBlockNumbers function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/order/IncreaseOrderUtils.sol#L84)

**Comment by Sk8erboi84** [comment]
> Hello, may I take this?

Hello, can you please pull from main please cause the signatures just got implemented

**Comment by ftupas** [comment]
> Hello, can you please pull from main please cause the signatures just got implemented

Gotcha will do 🤙

**Comment by sparqet** [comment]
Hi @ftupas ! Do you have any news on your issue ?

**Comment by ftupas** [comment]
Hey there, sorry haven't given an update. I managed to implement `validate_oracle_block_numbers` but still working on `process_order`. Will try to create the pr today or tomorrow
