### ISSUE TITLE
bug: Replace all SafeDispatcher by Dispatcher in the protocol

### ISSUE THREAD

**Issue by sparqet** [keep-starknet-strange/satoru#339]
# Bug Report

**Current behavior:**

We are now currently using SafeDispatcher that should allow us to call functions of a contract from another contract. But StarknetOS doesn't allow to catch failing contract calls : https://github.com/keep-starknet-strange/satoru/pull/289#pullrequestreview-1616246258

**Expected behavior:**

All SafeDispatcher should be replace by Dispatcher so that we can call functions from other contracts.

**Steps to reproduce:**

Replace all SafeDispatcher by Dispatcher in the protocol.

**Comment by rmzlb** [comment]
I cab take this one :) @abdelhamidbakhta

**Comment by abdelhamidbakhta** [comment]
> I can take this one :) @abdelhamidbakhta

let's go
