### ISSUE TITLE
feat: Remove chain module and directly use cairo native functions

### ISSUE THREAD

**Issue by zarboq** [keep-starknet-strange/satoru#343]
# Feature Request

**Describe the Feature Request**

We don't need to use chain module. We can directly use starknet native function to get info about the network (blocknumber, timestamp).

**Describe Preferred Solution**

Remove chain module and use native functions such as `starknet::info::get_block_number` where it's needed.

**Comment by Bal7hazar** [comment]
I can take it

**Comment by betacodd** [comment]
too fast ;(
