### ISSUE TITLE
bug: unstable nonce test

### ISSUE THREAD

**Issue by Bal7hazar** [keep-starknet-strange/satoru#347]
# Bug Report

**Satoru version:**

`main`

**Current behavior:**

The test `test_nonce_utils` is not stable.

It computes a hash between a deployed contract address and a nonce, but I think contract address in the test env is just a counter increased each time a contract is deployed, and since the test is using the test_lib setup, each time we will introduce a new deployed contract before the data store, so this test will fail.
So it is not a forever fix but it should be addressed in a dedicated PR I think, so far the tests are now working.

**Expected behavior:**

Have a test more stable, maybe we can just have a dedicated setup.

**Steps to reproduce:**

Check previous CI actions.

**Related code:**

```cairo
#[test]
fn test_nonce_utils() {
    // *********************************************************************************************
    // *                              SETUP                                                        *
    // *********************************************************************************************
    let (_, _, data_store) = setup();

    // *********************************************************************************************
    // *                              TEST LOGIC                                                   *
    // *********************************************************************************************

    let nonce = get_current_nonce(data_store).unwrap();
    assert(nonce == 0, 'Invalid nonce');

    let nonce = increment_nonce(data_store).unwrap();
    assert(nonce == 1, 'Invalid new nonce');

    let key = get_next_key(data_store).unwrap();
    assert(key == 0x282524aa644121524f01a2feb9a663ebc4afaf14924efa9565246d4ed9210b3, 'Invalid key');

    let nonce = get_current_nonce(data_store).unwrap();
    assert(nonce == 2, 'Invalid final nonce');
```

**Other information:**

**Comment by delaaxe** [comment]
i can fix this as i did the test

**Comment by Sk8erboi84** [comment]
Great! Assigned 🔥
