### ISSUE TITLE
Feat: Implement the functions in the `deposit_utils` library.

### ISSUE THREAD

**Issue by sparqet** [keep-starknet-strange/satoru#353]
## Description

Implement the `create_deposit` function in the `DepositUtils` library.

File: `src/deposit/deposit_utils.cairo`.

Function signature:
```rust
    /// Creates a deposit.
    fn create_deposit(
        ref self: TContractState,
        data_store: IDataStoreDispatcher,
        event_emitter: IEventEmitterDispatcher,
        deposit_vault: IDepositVaultDispatcher,
        account: ContractAddress,
        params: CreateDepositParams
    ) -> felt252;
```
---
Implement the `cancel_deposit` function in the `DepositUtils` library.

File: `src/deposit/deposit_utils.cairo`.

Function signature:
```rust
    /// Cancels a deposit, funds are sent back to the user
    fn cancel_deposit(
        ref self: TContractState,
        data_store: IDataStoreDispatcher,
        event_emitter: IEventEmitterDispatcher,
        deposit_vault: IDepositVaultDispatcher,
        key: felt252,
        keeper: ContractAddress,
        startingGas: felt252,
        reason: felt252,
        reason_bytes: Array<felt252>
);
```

## Acceptance criteria

- Function is implemented and well commented.
- Associated unit tests (nominal and failure) are implemented and passing.

## Resources

- [createDeposit function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/deposit/DepositUtils.sol#L62)
- [cancelDeposit function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/deposit/DepositUtils.sol#L148)

**Comment by 0xTitan** [comment]
Hello, can i work on this one ?

**Comment by sparqet** [comment]
of course !
