### ISSUE TITLE
Feat: Implement the functions in the `execute_deposit_utils` library.

### ISSUE THREAD

**Issue by sparqet** [keep-starknet-strange/satoru#354]
## Description

Implement the `execute_deposit` function in the `execute_deposit_utils` library.

File: `src/deposit/execute_deposit_utils.cairo`.

Function signature:
```rust
    /// Executes a deposit.
    fn execute_deposit(
        ref self: TContractState,
        params: ExecuteDepositParams
    );
```
---

Implement the `_execute_deposit` function in the `execute_deposit_utils` library.

File: `src/deposit/execute_deposit_utils.cairo`.

Function signature:
```rust
    /// Executes a deposit.
    fn _execute_deposit(
        ref self: TContractState,
        params: ExecuteDepositParams,
        _params: _ExecuteDepositParams
    ) -> u128;
```

---

Implement the `swap` function in the `execute_deposit_utils` library.

File: `src/deposit/execute_deposit_utils.cairo`.

Function signature:
```rust
    /// Executes a deposit.
    fn swap(
        ref self: TContractState,
        params: ExecuteDepositParams,
        swap_path: Array<ContractAddress>,
        initial_token: ContractAddress,
        input_amount: u128,
        market: ContractAddress,
        expected_output_token: ContractAddress,
        ui_fee_receiver: ContractAddress
    ) -> u128;
```

## Acceptance criteria

- Function is implemented and well commented.
- Associated unit tests (nominal and failure) are implemented and passing.

## Resources

- [executeDeposit function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/deposit/ExecuteDepositUtils.sol#L104)
- [_executeDeposit function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/deposit/ExecuteDepositUtils.sol#L250)
- [_executeDeposit function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/deposit/ExecuteDepositUtils.sol#L444)

**Comment by kasteph** [comment]
I'll give this one a shot 👀

**Comment by Sk8erboi84** [comment]
Sure, assigned 🔥

**Comment by kasteph** [comment]
Still working on this! Sorry for the lateness, I've been on holiday in the mountains ⛰️

**Comment by sparqet** [comment]
Hey @kasteph ! Do you have any news on your issue ?

**Comment by kasteph** [comment]
Hey @sparqet I'm working on it today!
