### ISSUE TITLE
Feat: Implement the functions in the `base_order_handler` contract.

### ISSUE THREAD

**Issue by sparqet** [keep-starknet-strange/satoru#356]
## Description

Implement the `get_execute_order_params` function in the `base_order_handler` library.

File: `src/exchange/base_order_handler.cairo`.

Function signature:
```rust
        /// Get the BaseOrderUtils.ExecuteOrderParams to execute an order.
        /// # Arguments
        /// * `key` - The the key of the order to execute.
        /// * `oracle_params` - The set price parameters for oracle.
        /// * `keeper` - The keeper executing the order.
        /// * `starting_gas` - The starting gas.
        fn get_execute_order_params(
            ref self: ContractState,
            key: felt252,
            oracle_params: SetPricesParams,
            keeper: ContractAddress,
            starting_gas: u128,
            secondary_order_type: SecondaryOrderType
        ) -> ExecuteOrderParams
```

## Acceptance criteria

- Function is implemented and well commented.
- Associated unit tests (nominal and failure) are implemented and passing.

## Resources

- [_getExecuteOrderParams function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/exchange/BaseOrderHandler.sol#L63)

**Comment by khaeljy** [comment]
Can I take this?

**Comment by sparqet** [comment]
Of course ! Assigned !

**Comment by dbejarano820** [comment]
is this still WIP? @khaeljy

**Comment by khaeljy** [comment]
> is this still WIP? @khaeljy

I'm really sorry, I haven't had time to get into it. You can assign this issue to someone else.
Next time I'll make sure I have enough time before asking for an issue.

**Comment by dbejarano820** [comment]
let me at it then!

**Comment by Sk8erboi84** [comment]
Ok I will assign it to you @dbejarano820 🔥
