### ISSUE TITLE
Feat: Implement the functions in the `withdrawal_utils` library.

### ISSUE THREAD

**Issue by sparqet** [keep-starknet-strange/satoru#359]
## Description

Implement the `create_withdrawal` function in the `withdrawal_utils` library.

File: `src/withdrawal/withdrawal_utils.cairo`.

Function signature:
```rust
    /// Creates a withdrawal in the withdrawal store.
    /// # Arguments
    /// * `data_store` - The data store where withdrawal data is stored.
    /// * `event_emitter` - The event emitter that is used to emit events.
    /// * `withdrawal_vault` - The withdrawal vault.
    /// * `account` - The account that initiated the withdrawal.
    /// * `params` - The parameters for creating the withdrawal.
    /// # Returns
    /// The unique identifier of the created withdrawal.
    #[inline(always)]
    fn create_withdrawal(
        data_store: IDataStoreDispatcher,
        event_emitter: IEventEmitterDispatcher,
        withdrawal_vault: IWithdrawalVaultDispatcher,
        account: ContractAddress,
        params: CreateWithdrawalParams
    ) -> felt252;
```

---

Implement the `execute_withdrawal` function in the `withdrawal_utils` library.

File: `src/withdrawal/withdrawal_utils.cairo`.

Function signature:
```rust
    /// Executes a withdrawal on the market.
    /// # Arguments
    /// * `params` - The parameters for executing the withdrawal.
    #[inline(always)]
    fn execute_withdrawal(params: ExecuteWithdrawalParams);
```

---

Implement the `cancel_withdrawal` function in the `withdrawal_utils` library.

File: `src/withdrawal/withdrawal_utils.cairo`.

Function signature:
```rust
    /// Cancel a withdrawal.
    /// # Arguments
    /// * `data_store` - The data store where withdrawal data is stored.
    /// * `event_emitter` - The event emitter that is used to emit events.
    /// * `withdrawal_vault` - The withdrawal vault.
    /// * `key` - The withdrawal key.
    /// * `keeper` - The keeper sending the transaction.
    /// * `starting_gas` - The starting gas for the transaction.
    /// * `reason` - The reason for cancelling.
    #[inline(always)]
    fn cancel_withdrawal(
        data_store: IDataStoreDispatcher,
        event_emitter: IEventEmitterDispatcher,
        withdrawal_vault: IWithdrawalVaultDispatcher,
        key: felt252,
        keeper: ContractAddress,
        starting_gas: u128,
        reason: felt252,
        reason_bytes: Array<felt252>,
    )
```

---

Implement the `execute_withdrawal_` function in the `withdrawal_utils` library.

File: `src/withdrawal/withdrawal_utils.cairo`.

Function signature:
```rust
    /// Executes a withdrawal.
    /// # Arguments
    /// * `params` - The parameters for executing the withdrawal.
    /// * `withdrawal` - The withdrawal to execute.
    /// # Returns
    /// The unique identifier of the created withdrawal.
    #[inline(always)]
    fn execute_withdrawal_(
        params: ExecuteWithdrawalParams, withdrawal: Withdrawal
    ) -> ExecuteWithdrawalResult;
```

---

Implement the `swap` function in the `withdrawal_utils` library.

File: `src/withdrawal/withdrawal_utils.cairo`.

Function signature:
```rust
    /// Swap tokens.
    /// # Arguments
    /// * `params` - The parameters for executing the withdrawal.
    /// * `market` - The Market.
    /// * `token_in` - The input token.
    /// * `swap_path` - The swap path.
    /// * `min_output_amount` - The minimum output amount.
    /// * `receiver` - The receiver of the swap output.
    /// * `ui_fee_receiver` - The ui fee receiver.
    /// * `should_unwrap_native_token` - Weither native token should be unwraped or not.
    /// # Returns
    /// Output token and its amount.
    #[inline(always)]
    fn swap(
        params: ExecuteWithdrawalParams,
        market: Market,
        token_in: ContractAddress,
        amount_in: u128,
        swap_path: Array<ContractAddress>,
        min_output_amount: u128,
        receiver: ContractAddress,
        ui_fee_receiver: ContractAddress,
        should_unwrap_native_token: bool,
    ) -> (ContractAddress, u128)
```

---

Implement the `swap` function in the `withdrawal_utils` library.

File: `src/withdrawal/withdrawal_utils.cairo`.

Function signature:
```rust
    #[inline(always)]
    fn get_output_amounts(
        params: ExecuteWithdrawalParams, market: Market, prices: MarketPrices, market_token_amount: u128
    ) -> (u128, u128)
```

## Acceptance criteria

- Function is implemented and well commented.
- Associated unit tests (nominal and failure) are implemented and passing.

## Resources

- [createWithdrawal function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/withdrawal/WithdrawalUtils.sol#L123)
- [executeWithdrawal function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/withdrawal/WithdrawalUtils.sol#L195)
- [cancelWithdrawal function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/withdrawal/WithdrawalUtils.sol#L253)
- [_executeWithdrawal function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/withdrawal/WithdrawalUtils.sol#L305)
- [swap function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/withdrawal/WithdrawalUtils.sol#L479)
- [_getOutputAmounts function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/withdrawal/WithdrawalUtils.sol#L516)

**Comment by ametel01** [comment]
happy to take this!

**Comment by Sk8erboi84** [comment]
Sure, assigned 🔥

**Comment by tevrat-aksoy** [comment]
hello @ametel01 .  `WithdrawalStoreUtils` and other StoreUtils libraries are implemented in `data_store.cairo` contract. 
For example to implement this function  `WithdrawalStoreUtils.get(params.dataStore, params.key);` you need to use `get_withdrawal` in data_store contract

**Comment by ametel01** [comment]
> hello @ametel01 . `WithdrawalStoreUtils` and other StoreUtils libraries are implemented in `data_store.cairo` contract. For example to implement this function `WithdrawalStoreUtils.get(params.dataStore, params.key);` you need to use `get_withdrawal` in data_store contract

Thanks for letting me know, i did implemented a mock for withdrawal_store_utils. Changing it now
