### ISSUE TITLE
Feat: Implement the functions in the `swap_utils` library.

### ISSUE THREAD

**Issue by Sk8erboi84** [keep-starknet-strange/satoru#360]
## Description

Implement the `swap` function in the `swap_utils` library.

File: `src/swap/swap_utils.cairo`.

Function signature:
```rust
fn swap(params: SwapParams) -> (ContractAddress, u128);
```
---

Implement the `_swap` function in the `swap_utils` library.

File: `src/swap/swap_utils.cairo`.

Function signature:
```rust
fn _swap(params: SwapParams, _params: _SwapParams) -> (ContractAddress, u128);
```
---

## Acceptance criteria

- Function is implemented and well commented.
- Associated unit tests (nominal and failure) are implemented and passing.

## Resources
- [swap function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/swap/SwapUtils.sol#L102)
- [_swap function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/swap/SwapUtils.sol#L184)

**Comment by FabienCoutant** [comment]
May I take this one? :)

**Comment by Sk8erboi84** [comment]
Yes sure! Assigned 🔥
