### ISSUE TITLE
Feat: Implement the functions in the `SwapHandler` contract.

### ISSUE THREAD

**Issue by sparqet** [keep-starknet-strange/satoru#361]
## Description

Implement the `swap` function in the `SwapHandler` contract.

File: `src/swap/swap_handler.cairo`.

Function signature:
```rust
    fn swap(ref self: ContractState, params: SwapParams) -> (ContractAddress, u128)
```

## Acceptance criteria

- Function is implemented and well commented.
- Associated unit tests (nominal and failure) are implemented and passing.

## Resources

- [swap function in GMX repo](https://github.com/keep-starknet-strange/satoru/blob/c0f1afe31e8215be4b88dd0402310f246e0718ea/src/swap/swap_handler.cairo#L58)

**Comment by Sk8erboi84** [comment]
Assigned 🔥
