### ISSUE TITLE
Feat: Implement the functions in the `position_pricing_utils` library.

### ISSUE THREAD

**Issue by Sk8erboi84** [keep-starknet-strange/satoru#362]
## Description

Implement the `get_price_impact_usd` function in the `position_pricing_utils` library.

File: `src/pricing/position_pricing_utils.cairo`.

Function signature:
```rust
fn get_price_impact_usd(params: GetPriceImpactUsdParams) -> i128;
```
---
Implement the `_get_price_impact_usd` function in the `position_pricing_utils` library.

File: `src/pricing/position_pricing_utils.cairo`.

Function signature:
```rust
fn get_price_impact_usd_(
    params: GetPriceImpactUsdParams,
    market: ContractAddress,
    open_interest_params: OpenInterestParams,
) -> i128;
```
---
Implement the `get_next_open_interest` function in the `position_pricing_utils` library.

File: `src/pricing/position_pricing_utils.cairo`.

Function signature:
```rust
fn get_next_open_interest(params: GetPriceImpactUsdParams) -> OpenInterestParams;
```
---
Implement the `get_next_open_interest_for_virtual_inventory` function in the `position_pricing_utils` library.

File: `src/pricing/position_pricing_utils.cairo`.

Function signature:
```rust
fn get_next_open_interest_for_virtual_inventory(
    params: GetPriceImpactUsdParams, virtual_inventory: i128,
) -> OpenInterestParams;
```
---
Implement the `get_next_open_interest_params` function in the `position_pricing_utils` library.

File: `src/pricing/position_pricing_utils.cairo`.

Function signature:
```rust
fn get_next_open_interest_params(
    params: GetPriceImpactUsdParams, long_open_interest: u128, short_open_interest: u128
) -> OpenInterestParams;
```
---
Implement the `get_position_fees` function in the `position_pricing_utils` library.

File: `src/pricing/position_pricing_utils.cairo`.

Function signature:
```rust
fn get_position_fees(params: GetPositionFeesParams) -> PositionFees;
```
---
Implement the `get_borrowing_fees` function in the `position_pricing_utils` library.

File: `src/pricing/position_pricing_utils.cairo`.

Function signature:
```rust
fn get_borrowing_fees(
    data_store: IDataStoreDispatcher, collateral_token_price: Price, borrowing_fee_usd: u128,
) -> PositionBorrowingFees;
```
---
Implement the `get_funding_fees` function in the `position_pricing_utils` library.

File: `src/pricing/position_pricing_utils.cairo`.

Function signature:
```rust
fn get_funding_fees(funding_fees: PositionFundingFees, position: Position,) -> PositionFundingFees;
```
---
Implement the `get_ui_fees` function in the `position_pricing_utils` library.

File: `src/pricing/position_pricing_utils.cairo`.

Function signature:
```rust
fn get_ui_fees(
    data_store: IDataStoreDispatcher,
    collateral_token_price: Price,
    size_delta_usd: u128,
    ui_fee_receiver: ContractAddress
) -> PositionUiFees;
```
---
Implement the `get_position_fees_after_referral` function in the `position_pricing_utils` library.

File: `src/pricing/position_pricing_utils.cairo`.

Function signature:
```rust
fn get_position_fees_after_referral(
    data_store: IDataStoreDispatcher,
    referral_storage: IReferralStorageDispatcher,
    collateral_token_price: Price,
    for_positive_impact: bool,
    account: ContractAddress,
    market: ContractAddress,
    size_delta_usd: u128,
) -> PositionFees;
```
---
## Acceptance criteria

- Function is implemented and well commented.
- Associated unit tests (nominal and failure) are implemented and passing.

## Resources
- [getPriceImpactUsd function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/pricing/PositionPricingUtils.sol#L140)
- [_getPriceImpactUsd function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/pricing/PositionPricingUtils.sol#L169)
- [getNextOpenInterest function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/pricing/PositionPricingUtils.sol#L206)
- [getNextOpenInterestForVirtualInventory function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/pricing/PositionPricingUtils.sol#L224)
- [getNextOpenInterestParams function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/pricing/PositionPricingUtils.sol#L256)
- [getPositionFees function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/pricing/PositionPricingUtils.sol#L297)
- [getBorrowingFees function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/pricing/PositionPricingUtils.sol#L367)
- [getFundingFees function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/pricing/PositionPricingUtils.sol#L382)
- [getUiFees function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/pricing/PositionPricingUtils.sol#L410)
- [getPositionFeesAfterReferral function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/pricing/PositionPricingUtils.sol#L437)

**Comment by ermvrs** [comment]
I think, `ReferralUtils.cairo`, `PricingUtils.cairo` and `Precision.cairo` has to be done to complete this issue.
