### ISSUE TITLE
Feat: Implement the functions in the `reader_pricing_utils` library.

### ISSUE THREAD

**Issue by Sk8erboi84** [keep-starknet-strange/satoru#389]
## Description

Implement the `get_swap_amount_out` function in the `reader_pricing_utils` library.

File: `src/reader/reader_pricing_utils.cairo`.

Function signature:
```rust
fn get_swap_amount_out(
    data_store: IDataStoreDispatcher,
    market: Market,
    prices: MarketPrices,
    token_in: ContractAddress,
    amount_in: u128,
    ui_fee_receiver: ContractAddress
) -> (u128, i128, SwapFees);
```
---
Implement the `get_execution_price` function in the `reader_pricing_utils` library.

File: `src/reader/reader_pricing_utils.cairo`.

Function signature:
```rust
fn get_execution_price(
    data_store: IDataStoreDispatcher,
    market: Market,
    index_token_price: Price,
    position_size_in_usd: u128,
    position_size_in_tokens: u128,
    size_delta_usd: i128,
    is_long: bool
) -> ExecutionPriceResult;
```
---
Implement the `get_swap_price_impact` function in the `reader_pricing_utils` library.

File: `src/reader/reader_pricing_utils.cairo`.

Function signature:
```rust
fn get_swap_price_impact(
    data_store: IDataStoreDispatcher,
    market: Market,
    token_in: ContractAddress,
    token_out: ContractAddress,
    amount_in: u128,
    token_in_price: Price,
    token_out_price: Price
) -> (i128, i128);
```
---

## Acceptance criteria

- Function is implemented and well commented.
- Associated unit tests (nominal and failure) are implemented and passing.

## Resources
- [getSwapAmountOut function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/reader/ReaderPricingUtils.sol#L57)
- [getExecutionPrice function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/reader/ReaderPricingUtils.sol#L144)
- [getSwapPriceImpact function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/reader/ReaderPricingUtils.sol#L186)

**Comment by StarkFishinator** [comment]
HI, can I take this one?

**Comment by zarboq** [comment]
Assigned :rocket:

**Comment by StarkFishinator** [comment]
Just to be sure I understood correctly. In the getSwapAmountOut function, [this](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/reader/ReaderPricingUtils.sol#L71) function is used. Should I implement also each function that is used in the getswapAmountOut function?
