### ISSUE TITLE
Feat: Implement the functions in the `referral_utils` `referral_storage` and `governable` library.

### ISSUE THREAD

**Issue by Sk8erboi84** [keep-starknet-strange/satoru#400]
## Description

Implement the `set_trader_referral_code` function in the `referral_utils` library.

File: `src/referral/referral_utils.cairo`.

Function signature:
```rust
fn set_trader_referral_code(
    referral_storage: IReferralStorageDispatcher, account: ContractAddress, referral_code: felt252);
```
---
Implement the `increment_affiliate_reward` function in the `referral_utils` library.

File: `src/referral/referral_utils.cairo`.

Function signature:
```rust
fn increment_affiliate_reward(
    data_store: IDataStoreDispatcher,
    event_emitter: IEventEmitterDispatcher,
    market: ContractAddress,
    token: ContractAddress,
    affiliate: ContractAddress,
    delta: u128
);
```
---
Implement the `increment_affiliate_reward` function in the `referral_utils` library.

File: `src/referral/referral_utils.cairo`.

Function signature:
```rust
fn get_referral_info(
    referral_storage: IReferralStorageDispatcher, trader: ContractAddress
) -> felt252, ContractAddress, u128, u128;
```
---
Implement the `claim_affiliate_rewards` function in the `referral_utils` library.

File: `src/referral/referral_utils.cairo`.

Function signature:
```rust
fn claim_affiliate_rewards(
    data_store: IDataStoreDispatcher,
    event_emitter: IEventEmitterDispatcher,
    market: ContractAddress,
    token: ContractAddress,
    affiliate: ContractAddress,
    receiver: ContractAddress
) -> u128;
```
---
## Acceptance criteria

- Function is implemented and well commented.
- Associated unit tests (nominal and failure) are implemented and passing.

## Resources
- [setTraderReferralCode function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/referral/ReferralUtils.sol#L25)
- [incrementAffiliateReward function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/referral/ReferralUtils.sol#L45)
- [getReferralInfo function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/referral/ReferralUtils.sol#L73)
- [claimAffiliateReward function in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/referral/ReferralUtils.sol#L108)

**Comment by FabienCoutant** [comment]
Can I continue on this? :)
