### ISSUE TITLE
feat: multiplication & division operator & `Store` for i128

### ISSUE THREAD

**Issue by zarboq** [keep-starknet-strange/satoru#406]
# Feature Request

Currently we're using u128 instead of i128 in many places because it's missing some traits. We need to implement those traits ourselves to be able to use i128.

Implement multiplication and division operator and `Store` for i128.

Add tests for it also.

**Comment by gaetbout** [comment]
Pick me

**Comment by delaaxe** [comment]
partially started [here](https://github.com/keep-starknet-strange/satoru/blob/main/src/utils/calc.cairo#L149-L175) and [here](https://github.com/keep-starknet-strange/satoru/blob/main/src/order/base_order_utils.cairo#L528-L554)

would be good to consolidate all conversion/calculation methods
