### ISSUE TITLE
feat: implement `apply_exponent_factor` function in precision.

### ISSUE THREAD

**Issue by zarboq** [keep-starknet-strange/satoru#417]
# Feature Request

precision functions have been implemented mostly but `apply_exponent_factor` is still pending. A non working implementation has been left in comment, maybe it can help. In solidity this function calls a function from an external math library (https://github.com/PaulRBerg/prb-math/blob/5959ef59f906d689c2472ed08797872a1cc00644/src/ud60x18/Math.sol#L481). We will probably need to re-implement it to obtain similar behavior.

**Describe Preferred Solution**

Implement `apply_exponent_factor` function. To verify it's working, you can test solidity function with arbitrary values and compare that your function is returning the same. It will be appreciated if you can write comparison results in your PR.

**Comment by StarkFishinator** [comment]
I can try this

**Comment by Sk8erboi84** [comment]
Assigned 🔥

**Comment by StarkFishinator** [comment]
Seems that the function we want relies on these : https://github.com/PaulRBerg/prb-math/blob/5959ef59f906d689c2472ed08797872a1cc00644/src/ud60x18/Math.sol#L270 and https://github.com/PaulRBerg/prb-math/blob/5959ef59f906d689c2472ed08797872a1cc00644/src/Common.sol#L54

Should we also implement them? It seems that these functions also relies on sub functions, and that at the end we will re implement the whole library
