### ISSUE TITLE
Feat: Implement the function in the `ExchangeRouter` contract.

### ISSUE THREAD

**Issue by Sk8erboi84** [keep-starknet-strange/satoru#429]
## Description

Implement the `send_wnt` function in the `ExchangeRouter` contract.

File: `src/router/exchange_router.cairo`.

Function signature:
```rust
fn send_wnt(ref self: TContractState, receiver: ContractAddress, amount: u128);
```
---
Implement the `send_wnt` function in the `ExchangeRouter` contract.

File: `src/router/exchange_router.cairo`.

Function signature:
```rust
fn send_tokens(ref self: TContractState, token: ContractAddress, receiver: ContractAddress, amount: u128)
```
---
Implement the `create_deposit` function in the `ExchangeRouter` contract.

File: `src/router/exchange_router.cairo`.

Function signature:
```rust
fn create_deposit(ref self: TContractState, params: CreateDepositParams) -> felt252
```
---
Implement the `cancel_deposit` function in the `ExchangeRouter` contract.

File: `src/router/exchange_router.cairo`.

Function signature:
```rust
fn cancel_deposit(ref self: TContractState, key: felt252);
```
---
Implement the `create_withdrawal` function in the `ExchangeRouter` contract.

File: `src/router/exchange_router.cairo`.

Function signature:
```rust
fn create_withdrawal(ref self: TContractState, params: CreateWithdrawalParams) -> felt252;
```
---
Implement the `cancel_withdrawal` function in the `ExchangeRouter` contract.

File: `src/router/exchange_router.cairo`.

Function signature:
```rust
fn cancel_withdrawal(ref self: TContractState, key: felt252);
```
---
Implement the `create_order` function in the `ExchangeRouter` contract.

File: `src/router/exchange_router.cairo`.

Function signature:
```rust
fn create_order(ref self: TContractState, params: CreateOrderParams) -> felt252;
```
---
Implement the `set_saved_callback_contract` function in the `ExchangeRouter` contract.

File: `src/router/exchange_router.cairo`.

Function signature:
```rust
fn set_saved_callback_contract(
        ref self: TContractState, market: ContractAddress, callback_contract: ContractAddress
    );
```
---
Implement the `simulate_execute_deposit` function in the `ExchangeRouter` contract.

File: `src/router/exchange_router.cairo`.

Function signature:
```rust
    fn simulate_execute_deposit(
        ref self: TContractState, key: felt252, simulated_oracle_params: SimulatePricesParams
    );
```
---
Implement the `simulate_execute_withdrawal` function in the `ExchangeRouter` contract.

File: `src/router/exchange_router.cairo`.

Function signature:
```rust
    fn simulate_execute_withdrawal(
        ref self: TContractState, key: felt252, simulated_oracle_params: SimulatePricesParams
    );
```
---
Implement the `simulate_execute_order` function in the `ExchangeRouter` contract.

File: `src/router/exchange_router.cairo`.

Function signature:
```rust
    fn simulate_execute_order(
        ref self: TContractState, key: felt252, simulated_oracle_params: SimulatePricesParams
    );
```
---
Implement the `update_order` function in the `ExchangeRouter` contract.

File: `src/router/exchange_router.cairo`.

Function signature:
```rust
    fn update_order(
        ref self: TContractState,
        key: felt252,
        size_delta_usd: u128,
        acceptable_price: u128,
        trigger_price: u128,
        min_output_amout: u128
    );
```
---
Implement the `cancel_order` function in the `ExchangeRouter` contract.

File: `src/router/exchange_router.cairo`.

Function signature:
```rust
    fn cancel_order(ref self: TContractState, key: felt252);
```
---
Implement the `claim_funding_fees` function in the `ExchangeRouter` contract.

File: `src/router/exchange_router.cairo`.

Function signature:
```rust
fn claim_funding_fees(
        ref self: TContractState,
        markets: Array<ContractAddress>,
        tokens: Array<ContractAddress>,
        receiver: ContractAddress
    ) -> Array<u128>;
```
---
Implement the `claim_collateral` function in the `ExchangeRouter` contract.

File: `src/router/exchange_router.cairo`.

Function signature:
```rust
    fn claim_collateral(
        ref self: TContractState,
        markets: Array<ContractAddress>,
        tokens: Array<ContractAddress>,
        time_keys: Array<u128>,
        receiver: ContractAddress
    ) -> Array<u128>;
```
---
Implement the `claim_affiliate_rewards` function in the `ExchangeRouter` contract.

File: `src/router/exchange_router.cairo`.

Function signature:
```rust
    fn claim_affiliate_rewards(
        ref self: TContractState,
        markets: Array<ContractAddress>,
        tokens: Array<ContractAddress>,
        receiver: ContractAddress
    ) -> Array<u128>;
```
---
Implement the `set_ui_fee_factor` function in the `ExchangeRouter` contract.

File: `src/router/exchange_router.cairo`.

Function signature:
```rust
    fn set_ui_fee_factor(ref self: TContractState, ui_fee_factor: u128);
```
---
Implement the `claim_ui_fees` function in the `ExchangeRouter` contract.

File: `src/router/exchange_router.cairo`.

Function signature:
```rust
    fn claim_ui_fees(
        ref self: TContractState,
        markets: Array<ContractAddress>,
        tokens: Array<ContractAddress>,
        receiver: ContractAddress
    ) -> Array<u128>;
```
---

## Acceptance criteria

- Function is implemented and well commented.
- Associated unit tests (nominal and failure) are implemented and passing.

## Resources

- [Functions in GMX repo](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/router/ExchangeRouter.sol)

**Comment by makluganteng** [comment]
Can i try picking this up ?

**Comment by sparqet** [comment]
Assigned !

**Comment by sparqet** [comment]
Hi @makluganteng ! How is it going ?
