### ISSUE TITLE
feat: finish `role_store` implementation

### ISSUE THREAD

**Issue by zarboq** [keep-starknet-strange/satoru#432]
# Feature Request

`role_store` has been partially done but some functions are missing. The issue consist of finishing it's implementation.

Following this PR: https://github.com/keep-starknet-strange/satoru/pull/420
And this issue: https://github.com/keep-starknet-strange/satoru/issues/241

Also add tests.

**Comment by ametel01** [comment]
Happy to take this

**Comment by sparqet** [comment]
Assigned !
