### ISSUE TITLE
Feat: Implement the function in the `market_utils` library. #3

### ISSUE THREAD

**Issue by sparqet** [keep-starknet-strange/satoru#435]
Implement from `getMaxPositionImpactFactor` function to `getExpectedMinTokenBalance` in the `market_utils` library.

Here is [MarketUtils.sol](https://github.com/gmx-io/gmx-synthetics/blob/77a2ff39f1414a105e8589d622bdb09ac3dd97d8/contracts/market/MarketUtils.sol)

**Comment by FabienCoutant** [comment]
Can I take this one ? :)

**Comment by 0xTrinityy** [comment]
Can i take this one ?

**Comment by abdelhamidbakhta** [comment]
> Can i take this one ?

Yes, assigned to you
