### ISSUE TITLE
Book: Add missing information in the smart-contract-architecture and in summary

### ISSUE THREAD

**Issue by Sk8erboi84** [keep-starknet-strange/satoru#452]
- Fill in any gaps in the smart contract architecture and the summary.
- Provide explanations for each libraries and contracts.
- Feel free to include any relevant additions to the book if you think they would be beneficial

Path:
```satoru\book\src\smart-contracts-architecture\```
```satoru\book\src\SUMMARY.md```
```satoru\book\src\README.md```

**Comment by axelizsak** [comment]
Yo Can I take this one ?

**Comment by Sk8erboi84** [comment]
Assigned 🔥
