### ISSUE TITLE
feat: check and integrate new semgrep rules

### ISSUE THREAD

**Issue by zarboq** [keep-starknet-strange/satoru#455]
# Feature Request

**Describe the Feature Request**

New semgrep rules were added in this [PR](https://github.com/keep-starknet-strange/satoru/pull/453). Add them to the current CI workflow and check that they being applied when creating a PR.

**Comment by loubna-msellek** [comment]
Hello I will try this one

**Comment by zarboq** [comment]
Assigned :rocket:

**Comment by ptisserand** [comment]
Hi, if this issue is still open I can work on it.
