### ISSUE TITLE
test: Improve tests of `base_order_handler` contract.

### ISSUE THREAD

**Issue by sparqet** [keep-starknet-strange/satoru#478]
## Description

Implement and improve tests of `base_order_handler` contract.

File: `test/exchange/base_order_handler.cairo`.

## Acceptance criteria

- Unit tests (nominal and failure) are implemented and passing.

**Comment by akhercha** [comment]
Hey, I can try this! 😁

**Comment by akhercha** [comment]
Just checking with you @zarboq ; is everything implemented here and can I start testing?
