### ISSUE TITLE
test: Improve tests of `liquidation_handler` contract.

### ISSUE THREAD

**Issue by sparqet** [keep-starknet-strange/satoru#479]
## Description

Implement and improve tests of `liquidation_handler ` contract.

File: `test/exchange/liquidation_handler.cairo`.

## Acceptance criteria

- Unit tests (nominal and failure) are implemented and passing.

**Comment by azurwastaken** [comment]
Hello, I would like to work on this :)

**Comment by azurwastaken** [comment]
Hello, I'd like to take this one :)

**Comment by tevrat-aksoy** [comment]
I can take this

**Comment by Sk8erboi84** [comment]
Assigned! 🔥

**Comment by Sk8erboi84** [comment]
Any updates ? @tevrat-aksoy

**Comment by tevrat-aksoy** [comment]
oracle_utils library not implemented yet. I cant complete the tests because of that

**Comment by zarboq** [comment]
Closed #589
