### ISSUE TITLE
test: Improve tests of `withdrawal_handler` contract.

### ISSUE THREAD

**Issue by sparqet** [keep-starknet-strange/satoru#480]
## Description

Implement and improve tests of `withdrawal_handler` contract.

File: `test/exchange/withdrawal_handler.cairo`.

## Acceptance criteria

- Unit tests (nominal and failure) are implemented and passing.

**Comment by 0xTitan** [comment]
Can i take this one ? Thank you.

**Comment by sparqet** [comment]
Of course !

**Comment by Sk8erboi84** [comment]
Any updates ? @0xTitan

**Comment by 0xTitan** [comment]
Hi, yes it should be ready by this friday. I was waiting for tests to be fixed with latest foundry version.
