### ISSUE TITLE
test: Improve tests of `reader` library.

### ISSUE THREAD

**Issue by sparqet** [keep-starknet-strange/satoru#491]
## Description

Implement and improve tests of `reader` contract.

File: `test/reader/reader.cairo`.

## Acceptance criteria

- Unit tests (nominal and failure) are implemented and passing.

**Comment by Akinbola247** [comment]
hi @sparqet  i will like to work on this

**Comment by sparqet** [comment]
Of course !

**Comment by Sk8erboi84** [comment]
Any updates ? @Akinbola247

**Comment by Akinbola247** [comment]
@sparqet it’s a work in progress. I’ll make a PR in no time.

**Comment by Akinbola247** [comment]
@sparqet here's a progress report, already added 10 more unit tests, in the test_reader. about four more to go. i'll make the PR once it's complete

**Comment by Akinbola247** [comment]
> Any updates ? @Akinbola247

@Sk8erboi84 i created a PR here #561 , it's still in draft, suggestion is required
