### ISSUE TITLE
test: Implement test of `record_transfer_in` function.

### ISSUE THREAD

**Issue by sparqet** [keep-starknet-strange/satoru#497]
## Description

Implement tests of `record_transfer_in` function : `given_normal_conditions_when_record_transfer_in_then_works`

File: `tests/deposit/test_deposit_vault.cairo`.

## Acceptance criteria

- Unit tests (nominal and failure) are implemented and passing.

**Comment by akhercha** [comment]
Happy to do this (& the quick implementation of `record_transfer_in`)!
