### ISSUE TITLE
feat: modify `data_store` behavior when getting structs.

### ISSUE THREAD

**Issue by zarboq** [keep-starknet-strange/satoru#532]
# Feature Request

**Describe the Feature Request**

In GMX, functions to get `Order`, `Deposit`, `Withdrawal`, `Market` and `Position`  return an empty struct if there is no associated object with the given key. In our implementation we are returning None, so it gives a different behavior an could lead to unexpected results. We should return Default struct instead.

**Describe Preferred Solution**

Modify the five concerned getter functions in `data_store.cairo` to return Default struct when there is no associated struct to given key.

**Comment by khaeljy** [comment]
Can I get this one, pls?

**Comment by zarboq** [comment]
Sure !
