### ISSUE TITLE
feat: Improve tests of position_utils library.

### ISSUE THREAD

**Issue by zarboq** [keep-starknet-strange/satoru#567]
# Feature Request

Tests for the following functions are missing:
   -  `will_collateral_be_sufficient()`
   - `update_funding_and_borrowing_state()`

Add tests for them.

**Describe Preferred Solution**

Add tests in `tests/position/test_position_utils.cairo` file

**Comment by FelixGibson** [comment]
I'd like to help with this

**Comment by zarboq** [comment]
Sure, I assigned you !

**Comment by codekaya** [comment]
I'd like to assign on this
